namespace U2Drawx64
{
	// Token: 0x0200000D RID: 13
	[global::Microsoft.VisualBasic.CompilerServices.DesignerGenerated]
	internal partial class frmDrawing : global::System.Windows.Forms.Form
	{
		// Token: 0x0600015F RID: 351 RVA: 0x000AC678 File Offset: 0x000AB678
		[global::System.Diagnostics.DebuggerNonUserCode]
		protected override void Dispose(bool disposing)
		{
			try
			{
				if (disposing && this.components != null)
				{
					this.components.Dispose();
				}
			}
			finally
			{
				base.Dispose(disposing);
			}
		}

		// Token: 0x06000160 RID: 352 RVA: 0x000AC6B8 File Offset: 0x000AB6B8
		[global::System.Diagnostics.DebuggerStepThrough]
		private void InitializeComponent()
		{
			this.components = new global::System.ComponentModel.Container();
			global::System.ComponentModel.ComponentResourceManager componentResourceManager = new global::System.ComponentModel.ComponentResourceManager(typeof(global::U2Drawx64.frmDrawing));
			this.GlControl1 = new global::OpenTK.GLControl();
			this.btnStraightLine = new global::System.Windows.Forms.Button();
			this.btnFreeDrawing = new global::System.Windows.Forms.Button();
			this.btnAngledLines = new global::System.Windows.Forms.Button();
			this.btnMeasuringLines = new global::System.Windows.Forms.Button();
			this.btnArrows = new global::System.Windows.Forms.Button();
			this.btnRectangle = new global::System.Windows.Forms.Button();
			this.btnEllipse = new global::System.Windows.Forms.Button();
			this.btnArc = new global::System.Windows.Forms.Button();
			this.btnext = new global::System.Windows.Forms.Button();
			this.txtDrawText = new global::System.Windows.Forms.TextBox();
			this.btnStamps = new global::System.Windows.Forms.Button();
			this.btnSelect = new global::System.Windows.Forms.Button();
			this.btnDelete = new global::System.Windows.Forms.Button();
			this.btnMove = new global::System.Windows.Forms.Button();
			this.btnRotate = new global::System.Windows.Forms.Button();
			this.btnEraseScreen = new global::System.Windows.Forms.Button();
			this.btnSymbol = new global::System.Windows.Forms.Button();
			this.btnNorthSymbol = new global::System.Windows.Forms.Button();
			this.btnGrid = new global::System.Windows.Forms.Button();
			this.btnCopy = new global::System.Windows.Forms.Button();
			this.btnPaste = new global::System.Windows.Forms.Button();
			this.btnUndo = new global::System.Windows.Forms.Button();
			this.cmdInsertImage = new global::System.Windows.Forms.Button();
			this.frSize = new global::System.Windows.Forms.GroupBox();
			this.btnSize2 = new global::System.Windows.Forms.Button();
			this.btnSize4 = new global::System.Windows.Forms.Button();
			this.btnSize3 = new global::System.Windows.Forms.Button();
			this.btnSize1 = new global::System.Windows.Forms.Button();
			this.fraLineStyle = new global::System.Windows.Forms.GroupBox();
			this.btnSolid = new global::System.Windows.Forms.Button();
			this.btnDash = new global::System.Windows.Forms.Button();
			this.frDirection = new global::System.Windows.Forms.GroupBox();
			this.btnDirectionNone = new global::System.Windows.Forms.Button();
			this.btnDirectionNorth = new global::System.Windows.Forms.Button();
			this.btnDirectionEast = new global::System.Windows.Forms.Button();
			this.btnDirectionSouth = new global::System.Windows.Forms.Button();
			this.btnDirectionWest = new global::System.Windows.Forms.Button();
			this.frInsertableTextPhrases = new global::System.Windows.Forms.GroupBox();
			this.btnTextRE = new global::System.Windows.Forms.Button();
			this.btnTextDW = new global::System.Windows.Forms.Button();
			this.btnTextBL = new global::System.Windows.Forms.Button();
			this.btnTextFL = new global::System.Windows.Forms.Button();
			this.btnTextPL = new global::System.Windows.Forms.Button();
			this.btnTextSW = new global::System.Windows.Forms.Button();
			this.btnTextCL = new global::System.Windows.Forms.Button();
			this.btnTextLA = new global::System.Windows.Forms.Button();
			this.btnTextNone = new global::System.Windows.Forms.Button();
			this.frListOfInsertableSymbols = new global::System.Windows.Forms.GroupBox();
			this.LineTypes = new global::System.Windows.Forms.ListBox();
			this.ToolTip1 = new global::System.Windows.Forms.ToolTip(this.components);
			this.btnResize = new global::System.Windows.Forms.Button();
			this.OpenFileDialog1 = new global::System.Windows.Forms.OpenFileDialog();
			this.Tools = new global::System.Windows.Forms.GroupBox();
			this.ToolStrip1 = new global::System.Windows.Forms.ToolStrip();
			this.ToolStripDropDownButton1 = new global::System.Windows.Forms.ToolStripDropDownButton();
			this.ToolStripMenuItem1 = new global::System.Windows.Forms.ToolStripMenuItem();
			this.btnFileOpen = new global::System.Windows.Forms.ToolStripMenuItem();
			this.ToolStripSeparator2 = new global::System.Windows.Forms.ToolStripSeparator();
			this.btnFileSave = new global::System.Windows.Forms.ToolStripMenuItem();
			this.btnFileSaveAs = new global::System.Windows.Forms.ToolStripMenuItem();
			this.ToolStripSeparator3 = new global::System.Windows.Forms.ToolStripSeparator();
			this.CloseToolStripMenuItem = new global::System.Windows.Forms.ToolStripMenuItem();
			this.ToolStripSeparator5 = new global::System.Windows.Forms.ToolStripSeparator();
			this.btnPrint = new global::System.Windows.Forms.ToolStripMenuItem();
			this.ToolStripSeparator4 = new global::System.Windows.Forms.ToolStripSeparator();
			this.ExitToolStripMenuItem = new global::System.Windows.Forms.ToolStripMenuItem();
			this.ToolStripLabel1 = new global::System.Windows.Forms.ToolStripLabel();
			this.cbTemplates = new global::System.Windows.Forms.ToolStripComboBox();
			this.btnInsertTemplate = new global::System.Windows.Forms.ToolStripButton();
			this.btnDeleteTemplate = new global::System.Windows.Forms.ToolStripButton();
			this.ToolStripSeparator1 = new global::System.Windows.Forms.ToolStripSeparator();
			this.ToolStripLabel2 = new global::System.Windows.Forms.ToolStripLabel();
			this.txtTemplateName = new global::System.Windows.Forms.ToolStripTextBox();
			this.btnSaveTemplate = new global::System.Windows.Forms.ToolStripButton();
			this.SaveFileDialog1 = new global::System.Windows.Forms.SaveFileDialog();
			this.PrintDialog1 = new global::System.Windows.Forms.PrintDialog();
			this.PrintDocument1 = new global::System.Drawing.Printing.PrintDocument();
			this.OpenFileDialog3 = new global::System.Windows.Forms.OpenFileDialog();
			this.frSize.SuspendLayout();
			this.fraLineStyle.SuspendLayout();
			this.frDirection.SuspendLayout();
			this.frInsertableTextPhrases.SuspendLayout();
			this.Tools.SuspendLayout();
			this.ToolStrip1.SuspendLayout();
			this.SuspendLayout();
			this.GlControl1.AutoValidate = global::System.Windows.Forms.AutoValidate.EnablePreventFocusChange;
			this.GlControl1.BackColor = global::System.Drawing.Color.White;
			global::System.Windows.Forms.Control glControl = this.GlControl1;
			global::System.Drawing.Point location = new global::System.Drawing.Point(254, 28);
			glControl.Location = location;
			this.GlControl1.Name = "GlControl1";
			global::System.Windows.Forms.Control glControl2 = this.GlControl1;
			global::System.Drawing.Size size = new global::System.Drawing.Size(667, 648);
			glControl2.Size = size;
			this.GlControl1.TabIndex = 0;
			this.GlControl1.VSync = false;
			this.btnStraightLine.BackColor = global::System.Drawing.Color.FromArgb(224, 224, 224);
			this.btnStraightLine.Cursor = global::System.Windows.Forms.Cursors.Default;
			this.btnStraightLine.Font = new global::System.Drawing.Font("Arial", 0.1f);
			this.btnStraightLine.ForeColor = global::System.Drawing.SystemColors.Control;
			this.btnStraightLine.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("btnStraightLine.Image");
			global::System.Windows.Forms.Control btnStraightLine = this.btnStraightLine;
			location = new global::System.Drawing.Point(6, 13);
			btnStraightLine.Location = location;
			this.btnStraightLine.Name = "btnStraightLine";
			this.btnStraightLine.RightToLeft = global::System.Windows.Forms.RightToLeft.No;
			global::System.Windows.Forms.Control btnStraightLine2 = this.btnStraightLine;
			size = new global::System.Drawing.Size(40, 36);
			btnStraightLine2.Size = size;
			this.btnStraightLine.TabIndex = 3;
			this.btnStraightLine.Tag = "StraightLine";
			this.btnStraightLine.TextAlign = global::System.Drawing.ContentAlignment.BottomCenter;
			this.ToolTip1.SetToolTip(this.btnStraightLine, "Straight Line");
			this.btnStraightLine.UseVisualStyleBackColor = false;
			this.btnFreeDrawing.BackColor = global::System.Drawing.Color.FromArgb(224, 224, 224);
			this.btnFreeDrawing.Cursor = global::System.Windows.Forms.Cursors.Default;
			this.btnFreeDrawing.Font = new global::System.Drawing.Font("Arial", 0.1f);
			this.btnFreeDrawing.ForeColor = global::System.Drawing.SystemColors.Control;
			this.btnFreeDrawing.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("btnFreeDrawing.Image");
			global::System.Windows.Forms.Control btnFreeDrawing = this.btnFreeDrawing;
			location = new global::System.Drawing.Point(6, 52);
			btnFreeDrawing.Location = location;
			this.btnFreeDrawing.Name = "btnFreeDrawing";
			this.btnFreeDrawing.RightToLeft = global::System.Windows.Forms.RightToLeft.No;
			global::System.Windows.Forms.Control btnFreeDrawing2 = this.btnFreeDrawing;
			size = new global::System.Drawing.Size(40, 36);
			btnFreeDrawing2.Size = size;
			this.btnFreeDrawing.TabIndex = 4;
			this.btnFreeDrawing.Tag = "FreeHand";
			this.btnFreeDrawing.TextAlign = global::System.Drawing.ContentAlignment.BottomCenter;
			this.ToolTip1.SetToolTip(this.btnFreeDrawing, "Pencil");
			this.btnFreeDrawing.UseVisualStyleBackColor = false;
			this.btnAngledLines.BackColor = global::System.Drawing.Color.FromArgb(224, 224, 224);
			this.btnAngledLines.Cursor = global::System.Windows.Forms.Cursors.Default;
			this.btnAngledLines.Font = new global::System.Drawing.Font("Arial", 1f);
			this.btnAngledLines.ForeColor = global::System.Drawing.SystemColors.Control;
			this.btnAngledLines.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("btnAngledLines.Image");
			global::System.Windows.Forms.Control btnAngledLines = this.btnAngledLines;
			location = new global::System.Drawing.Point(52, 13);
			btnAngledLines.Location = location;
			this.btnAngledLines.Name = "btnAngledLines";
			this.btnAngledLines.RightToLeft = global::System.Windows.Forms.RightToLeft.No;
			global::System.Windows.Forms.Control btnAngledLines2 = this.btnAngledLines;
			size = new global::System.Drawing.Size(40, 36);
			btnAngledLines2.Size = size;
			this.btnAngledLines.TabIndex = 5;
			this.btnAngledLines.Tag = "AngleLine";
			this.btnAngledLines.TextAlign = global::System.Drawing.ContentAlignment.BottomCenter;
			this.ToolTip1.SetToolTip(this.btnAngledLines, "Angled Line");
			this.btnAngledLines.UseVisualStyleBackColor = false;
			this.btnMeasuringLines.BackColor = global::System.Drawing.Color.FromArgb(224, 224, 224);
			this.btnMeasuringLines.Cursor = global::System.Windows.Forms.Cursors.Default;
			this.btnMeasuringLines.Font = new global::System.Drawing.Font("Tahoma", 1f, global::System.Drawing.FontStyle.Bold | global::System.Drawing.FontStyle.Italic);
			this.btnMeasuringLines.ForeColor = global::System.Drawing.SystemColors.Control;
			this.btnMeasuringLines.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("btnMeasuringLines.Image");
			global::System.Windows.Forms.Control btnMeasuringLines = this.btnMeasuringLines;
			location = new global::System.Drawing.Point(52, 53);
			btnMeasuringLines.Location = location;
			this.btnMeasuringLines.Name = "btnMeasuringLines";
			this.btnMeasuringLines.RightToLeft = global::System.Windows.Forms.RightToLeft.No;
			global::System.Windows.Forms.Control btnMeasuringLines2 = this.btnMeasuringLines;
			size = new global::System.Drawing.Size(40, 36);
			btnMeasuringLines2.Size = size;
			this.btnMeasuringLines.TabIndex = 6;
			this.btnMeasuringLines.Tag = "MeasuringLine";
			this.btnMeasuringLines.TextAlign = global::System.Drawing.ContentAlignment.BottomCenter;
			this.ToolTip1.SetToolTip(this.btnMeasuringLines, "Measuring Lines");
			this.btnMeasuringLines.UseVisualStyleBackColor = false;
			this.btnArrows.BackColor = global::System.Drawing.Color.FromArgb(224, 224, 224);
			this.btnArrows.Cursor = global::System.Windows.Forms.Cursors.Default;
			this.btnArrows.Font = new global::System.Drawing.Font("Arial", 8.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.btnArrows.ForeColor = global::System.Drawing.SystemColors.ControlText;
			this.btnArrows.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("btnArrows.Image");
			global::System.Windows.Forms.Control btnArrows = this.btnArrows;
			location = new global::System.Drawing.Point(6, 95);
			btnArrows.Location = location;
			this.btnArrows.Name = "btnArrows";
			this.btnArrows.RightToLeft = global::System.Windows.Forms.RightToLeft.No;
			global::System.Windows.Forms.Control btnArrows2 = this.btnArrows;
			size = new global::System.Drawing.Size(40, 36);
			btnArrows2.Size = size;
			this.btnArrows.TabIndex = 7;
			this.btnArrows.Tag = "Arrow";
			this.btnArrows.TextAlign = global::System.Drawing.ContentAlignment.BottomCenter;
			this.ToolTip1.SetToolTip(this.btnArrows, "Arrow");
			this.btnArrows.UseVisualStyleBackColor = false;
			this.btnRectangle.BackColor = global::System.Drawing.Color.FromArgb(224, 224, 224);
			this.btnRectangle.Cursor = global::System.Windows.Forms.Cursors.Default;
			this.btnRectangle.Font = new global::System.Drawing.Font("Arial", 0.1f);
			this.btnRectangle.ForeColor = global::System.Drawing.SystemColors.Control;
			this.btnRectangle.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("btnRectangle.Image");
			global::System.Windows.Forms.Control btnRectangle = this.btnRectangle;
			location = new global::System.Drawing.Point(6, 137);
			btnRectangle.Location = location;
			this.btnRectangle.Name = "btnRectangle";
			this.btnRectangle.RightToLeft = global::System.Windows.Forms.RightToLeft.No;
			global::System.Windows.Forms.Control btnRectangle2 = this.btnRectangle;
			size = new global::System.Drawing.Size(40, 36);
			btnRectangle2.Size = size;
			this.btnRectangle.TabIndex = 8;
			this.btnRectangle.Tag = "Rectangle";
			this.btnRectangle.TextAlign = global::System.Drawing.ContentAlignment.BottomCenter;
			this.ToolTip1.SetToolTip(this.btnRectangle, "Rectangle");
			this.btnRectangle.UseVisualStyleBackColor = false;
			this.btnEllipse.BackColor = global::System.Drawing.Color.FromArgb(224, 224, 224);
			this.btnEllipse.Cursor = global::System.Windows.Forms.Cursors.Default;
			this.btnEllipse.Font = new global::System.Drawing.Font("Arial", 0.1f);
			this.btnEllipse.ForeColor = global::System.Drawing.SystemColors.ControlText;
			this.btnEllipse.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("btnEllipse.Image");
			global::System.Windows.Forms.Control btnEllipse = this.btnEllipse;
			location = new global::System.Drawing.Point(52, 137);
			btnEllipse.Location = location;
			this.btnEllipse.Name = "btnEllipse";
			this.btnEllipse.RightToLeft = global::System.Windows.Forms.RightToLeft.No;
			global::System.Windows.Forms.Control btnEllipse2 = this.btnEllipse;
			size = new global::System.Drawing.Size(40, 36);
			btnEllipse2.Size = size;
			this.btnEllipse.TabIndex = 10;
			this.btnEllipse.Tag = "Circle";
			this.btnEllipse.TextAlign = global::System.Drawing.ContentAlignment.BottomCenter;
			this.ToolTip1.SetToolTip(this.btnEllipse, "Circle");
			this.btnEllipse.UseVisualStyleBackColor = false;
			this.btnArc.BackColor = global::System.Drawing.Color.FromArgb(224, 224, 224);
			this.btnArc.Cursor = global::System.Windows.Forms.Cursors.Default;
			this.btnArc.Font = new global::System.Drawing.Font("Arial", 0.1f);
			this.btnArc.ForeColor = global::System.Drawing.SystemColors.Control;
			this.btnArc.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("btnArc.Image");
			global::System.Windows.Forms.Control btnArc = this.btnArc;
			location = new global::System.Drawing.Point(52, 95);
			btnArc.Location = location;
			this.btnArc.Name = "btnArc";
			this.btnArc.RightToLeft = global::System.Windows.Forms.RightToLeft.No;
			global::System.Windows.Forms.Control btnArc2 = this.btnArc;
			size = new global::System.Drawing.Size(40, 36);
			btnArc2.Size = size;
			this.btnArc.TabIndex = 11;
			this.btnArc.Tag = "Arc";
			this.btnArc.TextAlign = global::System.Drawing.ContentAlignment.BottomCenter;
			this.ToolTip1.SetToolTip(this.btnArc, "Arc");
			this.btnArc.UseVisualStyleBackColor = false;
			this.btnext.BackColor = global::System.Drawing.Color.FromArgb(224, 224, 224);
			this.btnext.Cursor = global::System.Windows.Forms.Cursors.Default;
			this.btnext.Font = new global::System.Drawing.Font("Arial", 0.1f);
			this.btnext.ForeColor = global::System.Drawing.Color.FromArgb(224, 224, 224);
			this.btnext.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("btnext.Image");
			global::System.Windows.Forms.Control btnext = this.btnext;
			location = new global::System.Drawing.Point(52, 267);
			btnext.Location = location;
			this.btnext.Name = "btnext";
			this.btnext.RightToLeft = global::System.Windows.Forms.RightToLeft.No;
			global::System.Windows.Forms.Control btnext2 = this.btnext;
			size = new global::System.Drawing.Size(40, 36);
			btnext2.Size = size;
			this.btnext.TabIndex = 15;
			this.btnext.Tag = "Text";
			this.ToolTip1.SetToolTip(this.btnext, "Text");
			this.btnext.UseVisualStyleBackColor = false;
			global::System.Windows.Forms.Control txtDrawText = this.txtDrawText;
			location = new global::System.Drawing.Point(507, 304);
			txtDrawText.Location = location;
			this.txtDrawText.Multiline = true;
			this.txtDrawText.Name = "txtDrawText";
			global::System.Windows.Forms.Control txtDrawText2 = this.txtDrawText;
			size = new global::System.Drawing.Size(100, 20);
			txtDrawText2.Size = size;
			this.txtDrawText.TabIndex = 18;
			this.txtDrawText.Visible = false;
			this.btnStamps.BackColor = global::System.Drawing.Color.FromArgb(224, 224, 224);
			this.btnStamps.Cursor = global::System.Windows.Forms.Cursors.Default;
			this.btnStamps.Font = new global::System.Drawing.Font("Arial", 0.1f);
			this.btnStamps.ForeColor = global::System.Drawing.SystemColors.ControlText;
			this.btnStamps.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("btnStamps.Image");
			global::System.Windows.Forms.Control btnStamps = this.btnStamps;
			location = new global::System.Drawing.Point(6, 225);
			btnStamps.Location = location;
			this.btnStamps.Name = "btnStamps";
			this.btnStamps.RightToLeft = global::System.Windows.Forms.RightToLeft.No;
			global::System.Windows.Forms.Control btnStamps2 = this.btnStamps;
			size = new global::System.Drawing.Size(40, 36);
			btnStamps2.Size = size;
			this.btnStamps.TabIndex = 20;
			this.btnStamps.Tag = "Stamp";
			this.ToolTip1.SetToolTip(this.btnStamps, "Stamp");
			this.btnStamps.UseVisualStyleBackColor = false;
			this.btnSelect.BackColor = global::System.Drawing.Color.FromArgb(224, 224, 224);
			this.btnSelect.Cursor = global::System.Windows.Forms.Cursors.Default;
			this.btnSelect.Font = new global::System.Drawing.Font("Arial", 0.1f);
			this.btnSelect.ForeColor = global::System.Drawing.SystemColors.Control;
			this.btnSelect.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("btnSelect.Image");
			global::System.Windows.Forms.Control btnSelect = this.btnSelect;
			location = new global::System.Drawing.Point(6, 309);
			btnSelect.Location = location;
			this.btnSelect.Name = "btnSelect";
			this.btnSelect.RightToLeft = global::System.Windows.Forms.RightToLeft.No;
			global::System.Windows.Forms.Control btnSelect2 = this.btnSelect;
			size = new global::System.Drawing.Size(40, 36);
			btnSelect2.Size = size;
			this.btnSelect.TabIndex = 21;
			this.btnSelect.Tag = "Select";
			this.btnSelect.TextAlign = global::System.Drawing.ContentAlignment.BottomCenter;
			this.ToolTip1.SetToolTip(this.btnSelect, "Select");
			this.btnSelect.UseVisualStyleBackColor = false;
			this.btnDelete.BackColor = global::System.Drawing.Color.FromArgb(224, 224, 224);
			this.btnDelete.Cursor = global::System.Windows.Forms.Cursors.Default;
			this.btnDelete.Font = new global::System.Drawing.Font("Arial", 0.1f);
			this.btnDelete.ForeColor = global::System.Drawing.SystemColors.Control;
			this.btnDelete.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("btnDelete.Image");
			global::System.Windows.Forms.Control btnDelete = this.btnDelete;
			location = new global::System.Drawing.Point(6, 267);
			btnDelete.Location = location;
			this.btnDelete.Name = "btnDelete";
			this.btnDelete.RightToLeft = global::System.Windows.Forms.RightToLeft.No;
			global::System.Windows.Forms.Control btnDelete2 = this.btnDelete;
			size = new global::System.Drawing.Size(40, 36);
			btnDelete2.Size = size;
			this.btnDelete.TabIndex = 22;
			this.btnDelete.Tag = "Delete";
			this.btnDelete.TextAlign = global::System.Drawing.ContentAlignment.BottomCenter;
			this.ToolTip1.SetToolTip(this.btnDelete, "Delete");
			this.btnDelete.UseVisualStyleBackColor = false;
			this.btnMove.BackColor = global::System.Drawing.Color.FromArgb(224, 224, 224);
			this.btnMove.Cursor = global::System.Windows.Forms.Cursors.Default;
			this.btnMove.Font = new global::System.Drawing.Font("Arial", 0.1f);
			this.btnMove.ForeColor = global::System.Drawing.SystemColors.Control;
			this.btnMove.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("btnMove.Image");
			global::System.Windows.Forms.Control btnMove = this.btnMove;
			location = new global::System.Drawing.Point(52, 309);
			btnMove.Location = location;
			this.btnMove.Name = "btnMove";
			this.btnMove.RightToLeft = global::System.Windows.Forms.RightToLeft.No;
			global::System.Windows.Forms.Control btnMove2 = this.btnMove;
			size = new global::System.Drawing.Size(40, 36);
			btnMove2.Size = size;
			this.btnMove.TabIndex = 23;
			this.btnMove.Tag = "Move";
			this.btnMove.TextAlign = global::System.Drawing.ContentAlignment.BottomCenter;
			this.ToolTip1.SetToolTip(this.btnMove, "Move");
			this.btnMove.UseVisualStyleBackColor = false;
			this.btnRotate.BackColor = global::System.Drawing.Color.FromArgb(224, 224, 224);
			this.btnRotate.Cursor = global::System.Windows.Forms.Cursors.Default;
			this.btnRotate.Font = new global::System.Drawing.Font("Arial", 0.1f);
			this.btnRotate.ForeColor = global::System.Drawing.SystemColors.Control;
			this.btnRotate.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("btnRotate.Image");
			global::System.Windows.Forms.Control btnRotate = this.btnRotate;
			location = new global::System.Drawing.Point(52, 225);
			btnRotate.Location = location;
			this.btnRotate.Name = "btnRotate";
			this.btnRotate.RightToLeft = global::System.Windows.Forms.RightToLeft.No;
			global::System.Windows.Forms.Control btnRotate2 = this.btnRotate;
			size = new global::System.Drawing.Size(40, 36);
			btnRotate2.Size = size;
			this.btnRotate.TabIndex = 24;
			this.btnRotate.Tag = "Rotate";
			this.btnRotate.TextAlign = global::System.Drawing.ContentAlignment.BottomCenter;
			this.ToolTip1.SetToolTip(this.btnRotate, "Rotate");
			this.btnRotate.UseVisualStyleBackColor = false;
			this.btnEraseScreen.BackColor = global::System.Drawing.Color.FromArgb(224, 224, 224);
			this.btnEraseScreen.Cursor = global::System.Windows.Forms.Cursors.Default;
			this.btnEraseScreen.Font = new global::System.Drawing.Font("Arial", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.btnEraseScreen.ForeColor = global::System.Drawing.SystemColors.ControlText;
			this.btnEraseScreen.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("btnEraseScreen.Image");
			this.btnEraseScreen.ImageAlign = global::System.Drawing.ContentAlignment.TopCenter;
			global::System.Windows.Forms.Control btnEraseScreen = this.btnEraseScreen;
			location = new global::System.Drawing.Point(942, 74);
			btnEraseScreen.Location = location;
			this.btnEraseScreen.Name = "btnEraseScreen";
			this.btnEraseScreen.RightToLeft = global::System.Windows.Forms.RightToLeft.No;
			global::System.Windows.Forms.Control btnEraseScreen2 = this.btnEraseScreen;
			size = new global::System.Drawing.Size(54, 42);
			btnEraseScreen2.Size = size;
			this.btnEraseScreen.TabIndex = 25;
			this.btnEraseScreen.Text = "Clear";
			this.btnEraseScreen.TextAlign = global::System.Drawing.ContentAlignment.BottomCenter;
			this.btnEraseScreen.UseVisualStyleBackColor = false;
			this.btnSymbol.BackColor = global::System.Drawing.Color.FromArgb(224, 224, 224);
			this.btnSymbol.Cursor = global::System.Windows.Forms.Cursors.Default;
			this.btnSymbol.Font = new global::System.Drawing.Font("Arial", 8.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.btnSymbol.ForeColor = global::System.Drawing.SystemColors.ControlText;
			this.btnSymbol.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("btnSymbol.Image");
			global::System.Windows.Forms.Control btnSymbol = this.btnSymbol;
			location = new global::System.Drawing.Point(6, 181);
			btnSymbol.Location = location;
			this.btnSymbol.Name = "btnSymbol";
			this.btnSymbol.RightToLeft = global::System.Windows.Forms.RightToLeft.No;
			global::System.Windows.Forms.Control btnSymbol2 = this.btnSymbol;
			size = new global::System.Drawing.Size(40, 36);
			btnSymbol2.Size = size;
			this.btnSymbol.TabIndex = 28;
			this.btnSymbol.Tag = "Symbol";
			this.btnSymbol.TextAlign = global::System.Drawing.ContentAlignment.BottomCenter;
			this.ToolTip1.SetToolTip(this.btnSymbol, "Symbols");
			this.btnSymbol.UseVisualStyleBackColor = false;
			this.btnNorthSymbol.BackColor = global::System.Drawing.Color.FromArgb(224, 224, 224);
			this.btnNorthSymbol.Cursor = global::System.Windows.Forms.Cursors.Default;
			this.btnNorthSymbol.Font = new global::System.Drawing.Font("Arial", 1f);
			this.btnNorthSymbol.ForeColor = global::System.Drawing.SystemColors.Control;
			this.btnNorthSymbol.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("btnNorthSymbol.Image");
			global::System.Windows.Forms.Control btnNorthSymbol = this.btnNorthSymbol;
			location = new global::System.Drawing.Point(52, 181);
			btnNorthSymbol.Location = location;
			this.btnNorthSymbol.Name = "btnNorthSymbol";
			this.btnNorthSymbol.RightToLeft = global::System.Windows.Forms.RightToLeft.No;
			global::System.Windows.Forms.Control btnNorthSymbol2 = this.btnNorthSymbol;
			size = new global::System.Drawing.Size(40, 36);
			btnNorthSymbol2.Size = size;
			this.btnNorthSymbol.TabIndex = 29;
			this.btnNorthSymbol.Tag = "NorthSymbol";
			this.btnNorthSymbol.TextAlign = global::System.Drawing.ContentAlignment.BottomCenter;
			this.ToolTip1.SetToolTip(this.btnNorthSymbol, "North Symbol");
			this.btnNorthSymbol.UseVisualStyleBackColor = false;
			this.btnGrid.BackColor = global::System.Drawing.Color.FromArgb(224, 224, 224);
			this.btnGrid.Cursor = global::System.Windows.Forms.Cursors.Default;
			this.btnGrid.Font = new global::System.Drawing.Font("Arial", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.btnGrid.ForeColor = global::System.Drawing.SystemColors.ControlText;
			this.btnGrid.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("btnGrid.Image");
			this.btnGrid.ImageAlign = global::System.Drawing.ContentAlignment.TopCenter;
			global::System.Windows.Forms.Control btnGrid = this.btnGrid;
			location = new global::System.Drawing.Point(942, 122);
			btnGrid.Location = location;
			this.btnGrid.Name = "btnGrid";
			this.btnGrid.RightToLeft = global::System.Windows.Forms.RightToLeft.No;
			global::System.Windows.Forms.Control btnGrid2 = this.btnGrid;
			size = new global::System.Drawing.Size(54, 42);
			btnGrid2.Size = size;
			this.btnGrid.TabIndex = 44;
			this.btnGrid.Text = "Grid On";
			this.btnGrid.TextAlign = global::System.Drawing.ContentAlignment.BottomCenter;
			this.btnGrid.UseVisualStyleBackColor = false;
			this.btnCopy.BackColor = global::System.Drawing.Color.FromArgb(224, 224, 224);
			this.btnCopy.Cursor = global::System.Windows.Forms.Cursors.Default;
			this.btnCopy.Font = new global::System.Drawing.Font("Arial", 8f, global::System.Drawing.FontStyle.Bold);
			this.btnCopy.ForeColor = global::System.Drawing.SystemColors.ControlText;
			this.btnCopy.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("btnCopy.Image");
			this.btnCopy.ImageAlign = global::System.Drawing.ContentAlignment.TopCenter;
			global::System.Windows.Forms.Control btnCopy = this.btnCopy;
			location = new global::System.Drawing.Point(942, 170);
			btnCopy.Location = location;
			this.btnCopy.Name = "btnCopy";
			this.btnCopy.RightToLeft = global::System.Windows.Forms.RightToLeft.No;
			global::System.Windows.Forms.Control btnCopy2 = this.btnCopy;
			size = new global::System.Drawing.Size(54, 42);
			btnCopy2.Size = size;
			this.btnCopy.TabIndex = 129;
			this.btnCopy.Text = "&Copy ";
			this.btnCopy.TextAlign = global::System.Drawing.ContentAlignment.BottomCenter;
			this.btnCopy.UseVisualStyleBackColor = false;
			this.btnPaste.BackColor = global::System.Drawing.Color.FromArgb(224, 224, 224);
			this.btnPaste.Cursor = global::System.Windows.Forms.Cursors.Default;
			this.btnPaste.Font = new global::System.Drawing.Font("Arial", 8f, global::System.Drawing.FontStyle.Bold);
			this.btnPaste.ForeColor = global::System.Drawing.SystemColors.ControlText;
			this.btnPaste.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("btnPaste.Image");
			this.btnPaste.ImageAlign = global::System.Drawing.ContentAlignment.TopCenter;
			global::System.Windows.Forms.Control btnPaste = this.btnPaste;
			location = new global::System.Drawing.Point(942, 218);
			btnPaste.Location = location;
			this.btnPaste.Name = "btnPaste";
			this.btnPaste.RightToLeft = global::System.Windows.Forms.RightToLeft.No;
			global::System.Windows.Forms.Control btnPaste2 = this.btnPaste;
			size = new global::System.Drawing.Size(54, 42);
			btnPaste2.Size = size;
			this.btnPaste.TabIndex = 130;
			this.btnPaste.Text = "&Paste";
			this.btnPaste.TextAlign = global::System.Drawing.ContentAlignment.BottomCenter;
			this.btnPaste.UseVisualStyleBackColor = false;
			this.btnUndo.BackColor = global::System.Drawing.Color.FromArgb(224, 224, 224);
			this.btnUndo.Cursor = global::System.Windows.Forms.Cursors.Default;
			this.btnUndo.Font = new global::System.Drawing.Font("Arial", 8f, global::System.Drawing.FontStyle.Bold);
			this.btnUndo.ForeColor = global::System.Drawing.SystemColors.ControlText;
			this.btnUndo.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("btnUndo.Image");
			this.btnUndo.ImageAlign = global::System.Drawing.ContentAlignment.TopCenter;
			global::System.Windows.Forms.Control btnUndo = this.btnUndo;
			location = new global::System.Drawing.Point(942, 266);
			btnUndo.Location = location;
			this.btnUndo.Name = "btnUndo";
			this.btnUndo.RightToLeft = global::System.Windows.Forms.RightToLeft.No;
			global::System.Windows.Forms.Control btnUndo2 = this.btnUndo;
			size = new global::System.Drawing.Size(54, 42);
			btnUndo2.Size = size;
			this.btnUndo.TabIndex = 141;
			this.btnUndo.Text = "&Undo";
			this.btnUndo.TextAlign = global::System.Drawing.ContentAlignment.BottomCenter;
			this.btnUndo.UseVisualStyleBackColor = false;
			this.cmdInsertImage.BackColor = global::System.Drawing.Color.FromArgb(224, 224, 224);
			this.cmdInsertImage.Cursor = global::System.Windows.Forms.Cursors.Default;
			this.cmdInsertImage.Font = new global::System.Drawing.Font("Arial", 8f, global::System.Drawing.FontStyle.Bold);
			this.cmdInsertImage.ForeColor = global::System.Drawing.SystemColors.ControlText;
			this.cmdInsertImage.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("cmdInsertImage.Image");
			this.cmdInsertImage.ImageAlign = global::System.Drawing.ContentAlignment.TopCenter;
			global::System.Windows.Forms.Control cmdInsertImage = this.cmdInsertImage;
			location = new global::System.Drawing.Point(942, 314);
			cmdInsertImage.Location = location;
			this.cmdInsertImage.Name = "cmdInsertImage";
			this.cmdInsertImage.RightToLeft = global::System.Windows.Forms.RightToLeft.No;
			global::System.Windows.Forms.Control cmdInsertImage2 = this.cmdInsertImage;
			size = new global::System.Drawing.Size(54, 42);
			cmdInsertImage2.Size = size;
			this.cmdInsertImage.TabIndex = 142;
			this.cmdInsertImage.Text = "&Insert";
			this.cmdInsertImage.TextAlign = global::System.Drawing.ContentAlignment.BottomCenter;
			this.cmdInsertImage.UseVisualStyleBackColor = false;
			this.frSize.BackColor = global::System.Drawing.SystemColors.Control;
			this.frSize.Controls.Add(this.btnSize2);
			this.frSize.Controls.Add(this.btnSize4);
			this.frSize.Controls.Add(this.btnSize3);
			this.frSize.Controls.Add(this.btnSize1);
			this.frSize.Font = new global::System.Drawing.Font("Arial", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.frSize.ForeColor = global::System.Drawing.Color.FromArgb(128, 0, 0);
			global::System.Windows.Forms.Control frSize = this.frSize;
			location = new global::System.Drawing.Point(104, 176);
			frSize.Location = location;
			this.frSize.Name = "frSize";
			this.frSize.RightToLeft = global::System.Windows.Forms.RightToLeft.No;
			global::System.Windows.Forms.Control frSize2 = this.frSize;
			size = new global::System.Drawing.Size(57, 113);
			frSize2.Size = size;
			this.frSize.TabIndex = 143;
			this.frSize.TabStop = false;
			this.frSize.Text = "Size";
			this.btnSize2.BackColor = global::System.Drawing.SystemColors.Control;
			this.btnSize2.Cursor = global::System.Windows.Forms.Cursors.Default;
			this.btnSize2.Font = new global::System.Drawing.Font("Arial", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.btnSize2.ForeColor = global::System.Drawing.SystemColors.ControlText;
			this.btnSize2.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("btnSize2.Image");
			global::System.Windows.Forms.Control btnSize = this.btnSize2;
			location = new global::System.Drawing.Point(4, 44);
			btnSize.Location = location;
			this.btnSize2.Name = "btnSize2";
			this.btnSize2.RightToLeft = global::System.Windows.Forms.RightToLeft.No;
			global::System.Windows.Forms.Control btnSize2 = this.btnSize2;
			size = new global::System.Drawing.Size(49, 21);
			btnSize2.Size = size;
			this.btnSize2.TabIndex = 33;
			this.btnSize2.TextAlign = global::System.Drawing.ContentAlignment.BottomCenter;
			this.btnSize2.UseVisualStyleBackColor = false;
			this.btnSize4.BackColor = global::System.Drawing.SystemColors.Control;
			this.btnSize4.Cursor = global::System.Windows.Forms.Cursors.Default;
			this.btnSize4.Font = new global::System.Drawing.Font("Arial", 8.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.btnSize4.ForeColor = global::System.Drawing.SystemColors.ControlText;
			this.btnSize4.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("btnSize4.Image");
			global::System.Windows.Forms.Control btnSize3 = this.btnSize4;
			location = new global::System.Drawing.Point(4, 92);
			btnSize3.Location = location;
			this.btnSize4.Name = "btnSize4";
			this.btnSize4.RightToLeft = global::System.Windows.Forms.RightToLeft.No;
			global::System.Windows.Forms.Control btnSize4 = this.btnSize4;
			size = new global::System.Drawing.Size(49, 17);
			btnSize4.Size = size;
			this.btnSize4.TabIndex = 31;
			this.btnSize4.TextAlign = global::System.Drawing.ContentAlignment.BottomCenter;
			this.btnSize4.UseVisualStyleBackColor = false;
			this.btnSize3.BackColor = global::System.Drawing.SystemColors.Control;
			this.btnSize3.Cursor = global::System.Windows.Forms.Cursors.Default;
			this.btnSize3.Font = new global::System.Drawing.Font("Arial", 8.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.btnSize3.ForeColor = global::System.Drawing.SystemColors.ControlText;
			this.btnSize3.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("btnSize3.Image");
			global::System.Windows.Forms.Control btnSize5 = this.btnSize3;
			location = new global::System.Drawing.Point(4, 68);
			btnSize5.Location = location;
			this.btnSize3.Name = "btnSize3";
			this.btnSize3.RightToLeft = global::System.Windows.Forms.RightToLeft.No;
			global::System.Windows.Forms.Control btnSize6 = this.btnSize3;
			size = new global::System.Drawing.Size(49, 21);
			btnSize6.Size = size;
			this.btnSize3.TabIndex = 30;
			this.btnSize3.TextAlign = global::System.Drawing.ContentAlignment.BottomCenter;
			this.btnSize3.UseVisualStyleBackColor = false;
			this.btnSize1.BackColor = global::System.Drawing.SystemColors.Highlight;
			this.btnSize1.Cursor = global::System.Windows.Forms.Cursors.Default;
			this.btnSize1.Font = new global::System.Drawing.Font("Arial", 8.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.btnSize1.ForeColor = global::System.Drawing.SystemColors.ControlText;
			this.btnSize1.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("btnSize1.Image");
			global::System.Windows.Forms.Control btnSize7 = this.btnSize1;
			location = new global::System.Drawing.Point(4, 20);
			btnSize7.Location = location;
			this.btnSize1.Name = "btnSize1";
			this.btnSize1.RightToLeft = global::System.Windows.Forms.RightToLeft.No;
			global::System.Windows.Forms.Control btnSize8 = this.btnSize1;
			size = new global::System.Drawing.Size(49, 21);
			btnSize8.Size = size;
			this.btnSize1.TabIndex = 29;
			this.btnSize1.TextAlign = global::System.Drawing.ContentAlignment.BottomCenter;
			this.btnSize1.UseVisualStyleBackColor = false;
			this.fraLineStyle.BackColor = global::System.Drawing.SystemColors.Control;
			this.fraLineStyle.Controls.Add(this.btnSolid);
			this.fraLineStyle.Controls.Add(this.btnDash);
			this.fraLineStyle.Font = new global::System.Drawing.Font("Arial", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.fraLineStyle.ForeColor = global::System.Drawing.Color.FromArgb(128, 0, 0);
			global::System.Windows.Forms.Control fraLineStyle = this.fraLineStyle;
			location = new global::System.Drawing.Point(104, 104);
			fraLineStyle.Location = location;
			this.fraLineStyle.Name = "fraLineStyle";
			this.fraLineStyle.RightToLeft = global::System.Windows.Forms.RightToLeft.No;
			global::System.Windows.Forms.Control fraLineStyle2 = this.fraLineStyle;
			size = new global::System.Drawing.Size(57, 69);
			fraLineStyle2.Size = size;
			this.fraLineStyle.TabIndex = 144;
			this.fraLineStyle.TabStop = false;
			this.fraLineStyle.Text = "Style";
			this.btnSolid.BackColor = global::System.Drawing.SystemColors.Highlight;
			this.btnSolid.Cursor = global::System.Windows.Forms.Cursors.Default;
			this.btnSolid.Font = new global::System.Drawing.Font("Arial", 8.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.btnSolid.ForeColor = global::System.Drawing.SystemColors.ControlText;
			this.btnSolid.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("btnSolid.Image");
			global::System.Windows.Forms.Control btnSolid = this.btnSolid;
			location = new global::System.Drawing.Point(4, 40);
			btnSolid.Location = location;
			this.btnSolid.Name = "btnSolid";
			this.btnSolid.RightToLeft = global::System.Windows.Forms.RightToLeft.No;
			global::System.Windows.Forms.Control btnSolid2 = this.btnSolid;
			size = new global::System.Drawing.Size(49, 21);
			btnSolid2.Size = size;
			this.btnSolid.TabIndex = 32;
			this.btnSolid.TextAlign = global::System.Drawing.ContentAlignment.BottomCenter;
			this.btnSolid.UseVisualStyleBackColor = false;
			this.btnDash.BackColor = global::System.Drawing.SystemColors.Control;
			this.btnDash.Cursor = global::System.Windows.Forms.Cursors.Default;
			this.btnDash.Font = new global::System.Drawing.Font("Arial", 8.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.btnDash.ForeColor = global::System.Drawing.SystemColors.ControlText;
			this.btnDash.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("btnDash.Image");
			global::System.Windows.Forms.Control btnDash = this.btnDash;
			location = new global::System.Drawing.Point(4, 16);
			btnDash.Location = location;
			this.btnDash.Name = "btnDash";
			this.btnDash.RightToLeft = global::System.Windows.Forms.RightToLeft.No;
			global::System.Windows.Forms.Control btnDash2 = this.btnDash;
			size = new global::System.Drawing.Size(49, 21);
			btnDash2.Size = size;
			this.btnDash.TabIndex = 22;
			this.btnDash.TextAlign = global::System.Drawing.ContentAlignment.BottomCenter;
			this.btnDash.UseVisualStyleBackColor = false;
			this.frDirection.BackColor = global::System.Drawing.SystemColors.Control;
			this.frDirection.Controls.Add(this.btnDirectionNone);
			this.frDirection.Controls.Add(this.btnDirectionNorth);
			this.frDirection.Controls.Add(this.btnDirectionEast);
			this.frDirection.Controls.Add(this.btnDirectionSouth);
			this.frDirection.Controls.Add(this.btnDirectionWest);
			this.frDirection.Font = new global::System.Drawing.Font("Arial", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.frDirection.ForeColor = global::System.Drawing.Color.FromArgb(128, 0, 0);
			global::System.Windows.Forms.Control frDirection = this.frDirection;
			location = new global::System.Drawing.Point(104, 314);
			frDirection.Location = location;
			this.frDirection.Name = "frDirection";
			this.frDirection.RightToLeft = global::System.Windows.Forms.RightToLeft.No;
			global::System.Windows.Forms.Control frDirection2 = this.frDirection;
			size = new global::System.Drawing.Size(60, 224);
			frDirection2.Size = size;
			this.frDirection.TabIndex = 145;
			this.frDirection.TabStop = false;
			this.frDirection.Text = "Dir.";
			this.btnDirectionNone.BackColor = global::System.Drawing.SystemColors.Highlight;
			this.btnDirectionNone.Cursor = global::System.Windows.Forms.Cursors.Default;
			this.btnDirectionNone.Font = new global::System.Drawing.Font("Arial", 8f, global::System.Drawing.FontStyle.Bold);
			this.btnDirectionNone.ForeColor = global::System.Drawing.SystemColors.ControlText;
			global::System.Windows.Forms.Control btnDirectionNone = this.btnDirectionNone;
			location = new global::System.Drawing.Point(8, 16);
			btnDirectionNone.Location = location;
			this.btnDirectionNone.Name = "btnDirectionNone";
			this.btnDirectionNone.RightToLeft = global::System.Windows.Forms.RightToLeft.No;
			global::System.Windows.Forms.Control btnDirectionNone2 = this.btnDirectionNone;
			size = new global::System.Drawing.Size(46, 40);
			btnDirectionNone2.Size = size;
			this.btnDirectionNone.TabIndex = 93;
			this.btnDirectionNone.Text = "NONE";
			this.btnDirectionNone.UseVisualStyleBackColor = false;
			this.btnDirectionNorth.BackColor = global::System.Drawing.SystemColors.Control;
			this.btnDirectionNorth.Cursor = global::System.Windows.Forms.Cursors.Default;
			this.btnDirectionNorth.Font = new global::System.Drawing.Font("Arial", 8.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.btnDirectionNorth.ForeColor = global::System.Drawing.SystemColors.ControlText;
			this.btnDirectionNorth.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("btnDirectionNorth.Image");
			global::System.Windows.Forms.Control btnDirectionNorth = this.btnDirectionNorth;
			location = new global::System.Drawing.Point(8, 56);
			btnDirectionNorth.Location = location;
			this.btnDirectionNorth.Name = "btnDirectionNorth";
			this.btnDirectionNorth.RightToLeft = global::System.Windows.Forms.RightToLeft.No;
			global::System.Windows.Forms.Control btnDirectionNorth2 = this.btnDirectionNorth;
			size = new global::System.Drawing.Size(46, 40);
			btnDirectionNorth2.Size = size;
			this.btnDirectionNorth.TabIndex = 92;
			this.btnDirectionNorth.TextAlign = global::System.Drawing.ContentAlignment.BottomCenter;
			this.btnDirectionNorth.UseVisualStyleBackColor = false;
			this.btnDirectionEast.BackColor = global::System.Drawing.SystemColors.Control;
			this.btnDirectionEast.Cursor = global::System.Windows.Forms.Cursors.Default;
			this.btnDirectionEast.Font = new global::System.Drawing.Font("Arial", 8.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.btnDirectionEast.ForeColor = global::System.Drawing.SystemColors.ControlText;
			this.btnDirectionEast.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("btnDirectionEast.Image");
			global::System.Windows.Forms.Control btnDirectionEast = this.btnDirectionEast;
			location = new global::System.Drawing.Point(8, 96);
			btnDirectionEast.Location = location;
			this.btnDirectionEast.Name = "btnDirectionEast";
			this.btnDirectionEast.RightToLeft = global::System.Windows.Forms.RightToLeft.No;
			global::System.Windows.Forms.Control btnDirectionEast2 = this.btnDirectionEast;
			size = new global::System.Drawing.Size(46, 40);
			btnDirectionEast2.Size = size;
			this.btnDirectionEast.TabIndex = 91;
			this.btnDirectionEast.TextAlign = global::System.Drawing.ContentAlignment.BottomCenter;
			this.btnDirectionEast.UseVisualStyleBackColor = false;
			this.btnDirectionSouth.BackColor = global::System.Drawing.SystemColors.Control;
			this.btnDirectionSouth.Cursor = global::System.Windows.Forms.Cursors.Default;
			this.btnDirectionSouth.Font = new global::System.Drawing.Font("Arial", 8.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.btnDirectionSouth.ForeColor = global::System.Drawing.SystemColors.ControlText;
			this.btnDirectionSouth.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("btnDirectionSouth.Image");
			global::System.Windows.Forms.Control btnDirectionSouth = this.btnDirectionSouth;
			location = new global::System.Drawing.Point(8, 136);
			btnDirectionSouth.Location = location;
			this.btnDirectionSouth.Name = "btnDirectionSouth";
			this.btnDirectionSouth.RightToLeft = global::System.Windows.Forms.RightToLeft.No;
			global::System.Windows.Forms.Control btnDirectionSouth2 = this.btnDirectionSouth;
			size = new global::System.Drawing.Size(46, 40);
			btnDirectionSouth2.Size = size;
			this.btnDirectionSouth.TabIndex = 90;
			this.btnDirectionSouth.TextAlign = global::System.Drawing.ContentAlignment.BottomCenter;
			this.btnDirectionSouth.UseVisualStyleBackColor = false;
			this.btnDirectionWest.BackColor = global::System.Drawing.SystemColors.Control;
			this.btnDirectionWest.Cursor = global::System.Windows.Forms.Cursors.Default;
			this.btnDirectionWest.Font = new global::System.Drawing.Font("Arial", 8.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.btnDirectionWest.ForeColor = global::System.Drawing.SystemColors.ControlText;
			this.btnDirectionWest.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("btnDirectionWest.Image");
			global::System.Windows.Forms.Control btnDirectionWest = this.btnDirectionWest;
			location = new global::System.Drawing.Point(8, 176);
			btnDirectionWest.Location = location;
			this.btnDirectionWest.Name = "btnDirectionWest";
			this.btnDirectionWest.RightToLeft = global::System.Windows.Forms.RightToLeft.No;
			global::System.Windows.Forms.Control btnDirectionWest2 = this.btnDirectionWest;
			size = new global::System.Drawing.Size(46, 40);
			btnDirectionWest2.Size = size;
			this.btnDirectionWest.TabIndex = 89;
			this.btnDirectionWest.TextAlign = global::System.Drawing.ContentAlignment.BottomCenter;
			this.btnDirectionWest.UseVisualStyleBackColor = false;
			this.frInsertableTextPhrases.BackColor = global::System.Drawing.SystemColors.Control;
			this.frInsertableTextPhrases.Controls.Add(this.btnTextRE);
			this.frInsertableTextPhrases.Controls.Add(this.btnTextDW);
			this.frInsertableTextPhrases.Controls.Add(this.btnTextBL);
			this.frInsertableTextPhrases.Controls.Add(this.btnTextFL);
			this.frInsertableTextPhrases.Controls.Add(this.btnTextPL);
			this.frInsertableTextPhrases.Controls.Add(this.btnTextSW);
			this.frInsertableTextPhrases.Controls.Add(this.btnTextCL);
			this.frInsertableTextPhrases.Controls.Add(this.btnTextLA);
			this.frInsertableTextPhrases.Controls.Add(this.btnTextNone);
			this.frInsertableTextPhrases.Font = new global::System.Drawing.Font("Arial", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.frInsertableTextPhrases.ForeColor = global::System.Drawing.Color.FromArgb(128, 0, 0);
			global::System.Windows.Forms.Control frInsertableTextPhrases = this.frInsertableTextPhrases;
			location = new global::System.Drawing.Point(192, 87);
			frInsertableTextPhrases.Location = location;
			this.frInsertableTextPhrases.Name = "frInsertableTextPhrases";
			this.frInsertableTextPhrases.RightToLeft = global::System.Windows.Forms.RightToLeft.No;
			global::System.Windows.Forms.Control frInsertableTextPhrases2 = this.frInsertableTextPhrases;
			size = new global::System.Drawing.Size(56, 304);
			frInsertableTextPhrases2.Size = size;
			this.frInsertableTextPhrases.TabIndex = 146;
			this.frInsertableTextPhrases.TabStop = false;
			this.frInsertableTextPhrases.Text = "Text";
			this.btnTextRE.BackColor = global::System.Drawing.SystemColors.Control;
			this.btnTextRE.Cursor = global::System.Windows.Forms.Cursors.Default;
			this.btnTextRE.Font = new global::System.Drawing.Font("Arial", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.btnTextRE.ForeColor = global::System.Drawing.SystemColors.ControlText;
			global::System.Windows.Forms.Control btnTextRE = this.btnTextRE;
			location = new global::System.Drawing.Point(6, 272);
			btnTextRE.Location = location;
			this.btnTextRE.Name = "btnTextRE";
			this.btnTextRE.RightToLeft = global::System.Windows.Forms.RightToLeft.No;
			global::System.Windows.Forms.Control btnTextRE2 = this.btnTextRE;
			size = new global::System.Drawing.Size(40, 25);
			btnTextRE2.Size = size;
			this.btnTextRE.TabIndex = 74;
			this.btnTextRE.Text = "RE";
			this.btnTextRE.UseVisualStyleBackColor = false;
			this.btnTextDW.BackColor = global::System.Drawing.SystemColors.Control;
			this.btnTextDW.Cursor = global::System.Windows.Forms.Cursors.Default;
			this.btnTextDW.Font = new global::System.Drawing.Font("Arial", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.btnTextDW.ForeColor = global::System.Drawing.SystemColors.ControlText;
			global::System.Windows.Forms.Control btnTextDW = this.btnTextDW;
			location = new global::System.Drawing.Point(6, 240);
			btnTextDW.Location = location;
			this.btnTextDW.Name = "btnTextDW";
			this.btnTextDW.RightToLeft = global::System.Windows.Forms.RightToLeft.No;
			global::System.Windows.Forms.Control btnTextDW2 = this.btnTextDW;
			size = new global::System.Drawing.Size(40, 25);
			btnTextDW2.Size = size;
			this.btnTextDW.TabIndex = 73;
			this.btnTextDW.Text = "DW";
			this.btnTextDW.UseVisualStyleBackColor = false;
			this.btnTextBL.BackColor = global::System.Drawing.SystemColors.Control;
			this.btnTextBL.Cursor = global::System.Windows.Forms.Cursors.Default;
			this.btnTextBL.Font = new global::System.Drawing.Font("Arial", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.btnTextBL.ForeColor = global::System.Drawing.SystemColors.ControlText;
			global::System.Windows.Forms.Control btnTextBL = this.btnTextBL;
			location = new global::System.Drawing.Point(6, 208);
			btnTextBL.Location = location;
			this.btnTextBL.Name = "btnTextBL";
			this.btnTextBL.RightToLeft = global::System.Windows.Forms.RightToLeft.No;
			global::System.Windows.Forms.Control btnTextBL2 = this.btnTextBL;
			size = new global::System.Drawing.Size(40, 25);
			btnTextBL2.Size = size;
			this.btnTextBL.TabIndex = 72;
			this.btnTextBL.Text = "BL";
			this.btnTextBL.UseVisualStyleBackColor = false;
			this.btnTextFL.BackColor = global::System.Drawing.SystemColors.Control;
			this.btnTextFL.Cursor = global::System.Windows.Forms.Cursors.Default;
			this.btnTextFL.Font = new global::System.Drawing.Font("Arial", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.btnTextFL.ForeColor = global::System.Drawing.SystemColors.ControlText;
			global::System.Windows.Forms.Control btnTextFL = this.btnTextFL;
			location = new global::System.Drawing.Point(6, 176);
			btnTextFL.Location = location;
			this.btnTextFL.Name = "btnTextFL";
			this.btnTextFL.RightToLeft = global::System.Windows.Forms.RightToLeft.No;
			global::System.Windows.Forms.Control btnTextFL2 = this.btnTextFL;
			size = new global::System.Drawing.Size(40, 25);
			btnTextFL2.Size = size;
			this.btnTextFL.TabIndex = 71;
			this.btnTextFL.Text = "FL";
			this.btnTextFL.UseVisualStyleBackColor = false;
			this.btnTextPL.BackColor = global::System.Drawing.SystemColors.Control;
			this.btnTextPL.Cursor = global::System.Windows.Forms.Cursors.Default;
			this.btnTextPL.Font = new global::System.Drawing.Font("Arial", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.btnTextPL.ForeColor = global::System.Drawing.SystemColors.ControlText;
			global::System.Windows.Forms.Control btnTextPL = this.btnTextPL;
			location = new global::System.Drawing.Point(6, 144);
			btnTextPL.Location = location;
			this.btnTextPL.Name = "btnTextPL";
			this.btnTextPL.RightToLeft = global::System.Windows.Forms.RightToLeft.No;
			global::System.Windows.Forms.Control btnTextPL2 = this.btnTextPL;
			size = new global::System.Drawing.Size(40, 25);
			btnTextPL2.Size = size;
			this.btnTextPL.TabIndex = 70;
			this.btnTextPL.Text = "PL";
			this.btnTextPL.UseVisualStyleBackColor = false;
			this.btnTextSW.BackColor = global::System.Drawing.SystemColors.Control;
			this.btnTextSW.Cursor = global::System.Windows.Forms.Cursors.Default;
			this.btnTextSW.Font = new global::System.Drawing.Font("Arial", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.btnTextSW.ForeColor = global::System.Drawing.SystemColors.ControlText;
			global::System.Windows.Forms.Control btnTextSW = this.btnTextSW;
			location = new global::System.Drawing.Point(6, 112);
			btnTextSW.Location = location;
			this.btnTextSW.Name = "btnTextSW";
			this.btnTextSW.RightToLeft = global::System.Windows.Forms.RightToLeft.No;
			global::System.Windows.Forms.Control btnTextSW2 = this.btnTextSW;
			size = new global::System.Drawing.Size(40, 25);
			btnTextSW2.Size = size;
			this.btnTextSW.TabIndex = 69;
			this.btnTextSW.Text = "SW";
			this.btnTextSW.UseVisualStyleBackColor = false;
			this.btnTextCL.BackColor = global::System.Drawing.SystemColors.Control;
			this.btnTextCL.Cursor = global::System.Windows.Forms.Cursors.Default;
			this.btnTextCL.Font = new global::System.Drawing.Font("Arial", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.btnTextCL.ForeColor = global::System.Drawing.SystemColors.ControlText;
			global::System.Windows.Forms.Control btnTextCL = this.btnTextCL;
			location = new global::System.Drawing.Point(6, 80);
			btnTextCL.Location = location;
			this.btnTextCL.Name = "btnTextCL";
			this.btnTextCL.RightToLeft = global::System.Windows.Forms.RightToLeft.No;
			global::System.Windows.Forms.Control btnTextCL2 = this.btnTextCL;
			size = new global::System.Drawing.Size(40, 25);
			btnTextCL2.Size = size;
			this.btnTextCL.TabIndex = 68;
			this.btnTextCL.Text = "CL";
			this.btnTextCL.UseVisualStyleBackColor = false;
			this.btnTextLA.BackColor = global::System.Drawing.SystemColors.Control;
			this.btnTextLA.Cursor = global::System.Windows.Forms.Cursors.Default;
			this.btnTextLA.Font = new global::System.Drawing.Font("Arial", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.btnTextLA.ForeColor = global::System.Drawing.SystemColors.ControlText;
			global::System.Windows.Forms.Control btnTextLA = this.btnTextLA;
			location = new global::System.Drawing.Point(6, 48);
			btnTextLA.Location = location;
			this.btnTextLA.Name = "btnTextLA";
			this.btnTextLA.RightToLeft = global::System.Windows.Forms.RightToLeft.No;
			global::System.Windows.Forms.Control btnTextLA2 = this.btnTextLA;
			size = new global::System.Drawing.Size(40, 25);
			btnTextLA2.Size = size;
			this.btnTextLA.TabIndex = 67;
			this.btnTextLA.Text = "L.A.";
			this.btnTextLA.UseVisualStyleBackColor = false;
			this.btnTextNone.BackColor = global::System.Drawing.SystemColors.Highlight;
			this.btnTextNone.Cursor = global::System.Windows.Forms.Cursors.Default;
			this.btnTextNone.Font = new global::System.Drawing.Font("Arial", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.btnTextNone.ForeColor = global::System.Drawing.SystemColors.ControlText;
			global::System.Windows.Forms.Control btnTextNone = this.btnTextNone;
			location = new global::System.Drawing.Point(6, 16);
			btnTextNone.Location = location;
			this.btnTextNone.Name = "btnTextNone";
			this.btnTextNone.RightToLeft = global::System.Windows.Forms.RightToLeft.No;
			global::System.Windows.Forms.Control btnTextNone2 = this.btnTextNone;
			size = new global::System.Drawing.Size(40, 25);
			btnTextNone2.Size = size;
			this.btnTextNone.TabIndex = 19;
			this.btnTextNone.TextAlign = global::System.Drawing.ContentAlignment.BottomCenter;
			this.btnTextNone.UseVisualStyleBackColor = false;
			this.frListOfInsertableSymbols.BackColor = global::System.Drawing.SystemColors.Control;
			this.frListOfInsertableSymbols.Font = new global::System.Drawing.Font("Arial", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.frListOfInsertableSymbols.ForeColor = global::System.Drawing.Color.FromArgb(128, 0, 0);
			global::System.Windows.Forms.Control frListOfInsertableSymbols = this.frListOfInsertableSymbols;
			location = new global::System.Drawing.Point(168, 104);
			frListOfInsertableSymbols.Location = location;
			this.frListOfInsertableSymbols.Name = "frListOfInsertableSymbols";
			this.frListOfInsertableSymbols.RightToLeft = global::System.Windows.Forms.RightToLeft.No;
			global::System.Windows.Forms.Control frListOfInsertableSymbols2 = this.frListOfInsertableSymbols;
			size = new global::System.Drawing.Size(72, 504);
			frListOfInsertableSymbols2.Size = size;
			this.frListOfInsertableSymbols.TabIndex = 147;
			this.frListOfInsertableSymbols.TabStop = false;
			this.frListOfInsertableSymbols.Text = "Symbols";
			this.LineTypes.FormattingEnabled = true;
			global::System.Windows.Forms.Control lineTypes = this.LineTypes;
			location = new global::System.Drawing.Point(108, 427);
			lineTypes.Location = location;
			this.LineTypes.Name = "LineTypes";
			global::System.Windows.Forms.Control lineTypes2 = this.LineTypes;
			size = new global::System.Drawing.Size(140, 303);
			lineTypes2.Size = size;
			this.LineTypes.TabIndex = 148;
			this.LineTypes.Visible = false;
			this.btnResize.BackColor = global::System.Drawing.Color.FromArgb(224, 224, 224);
			this.btnResize.Cursor = global::System.Windows.Forms.Cursors.Default;
			this.btnResize.Font = new global::System.Drawing.Font("Arial", 0.1f);
			this.btnResize.ForeColor = global::System.Drawing.SystemColors.Control;
			this.btnResize.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("btnResize.Image");
			global::System.Windows.Forms.Control btnResize = this.btnResize;
			location = new global::System.Drawing.Point(6, 351);
			btnResize.Location = location;
			this.btnResize.Name = "btnResize";
			this.btnResize.RightToLeft = global::System.Windows.Forms.RightToLeft.No;
			global::System.Windows.Forms.Control btnResize2 = this.btnResize;
			size = new global::System.Drawing.Size(40, 36);
			btnResize2.Size = size;
			this.btnResize.TabIndex = 150;
			this.btnResize.Tag = "Resize";
			this.btnResize.Text = "Resize";
			this.btnResize.TextAlign = global::System.Drawing.ContentAlignment.BottomCenter;
			this.ToolTip1.SetToolTip(this.btnResize, "Resize");
			this.btnResize.UseVisualStyleBackColor = false;
			this.OpenFileDialog1.Filter = "Image .jpg |*.jpg";
			this.Tools.BackColor = global::System.Drawing.Color.DarkCyan;
			this.Tools.Controls.Add(this.btnStraightLine);
			this.Tools.Controls.Add(this.btnFreeDrawing);
			this.Tools.Controls.Add(this.btnAngledLines);
			this.Tools.Controls.Add(this.btnMeasuringLines);
			this.Tools.Controls.Add(this.btnArrows);
			this.Tools.Controls.Add(this.btnRectangle);
			this.Tools.Controls.Add(this.btnEllipse);
			this.Tools.Controls.Add(this.btnResize);
			this.Tools.Controls.Add(this.btnArc);
			this.Tools.Controls.Add(this.btnext);
			this.Tools.Controls.Add(this.btnStamps);
			this.Tools.Controls.Add(this.btnSelect);
			this.Tools.Controls.Add(this.btnDelete);
			this.Tools.Controls.Add(this.btnMove);
			this.Tools.Controls.Add(this.btnRotate);
			this.Tools.Controls.Add(this.btnSymbol);
			this.Tools.Controls.Add(this.btnNorthSymbol);
			global::System.Windows.Forms.Control tools = this.Tools;
			location = new global::System.Drawing.Point(0, 46);
			tools.Location = location;
			this.Tools.Name = "Tools";
			global::System.Windows.Forms.Control tools2 = this.Tools;
			size = new global::System.Drawing.Size(103, 406);
			tools2.Size = size;
			this.Tools.TabIndex = 157;
			this.Tools.TabStop = false;
			this.Tools.Text = "Tools";
			this.ToolStrip1.BackColor = global::System.Drawing.Color.Silver;
			this.ToolStrip1.GripStyle = global::System.Windows.Forms.ToolStripGripStyle.Hidden;
			this.ToolStrip1.Items.AddRange(new global::System.Windows.Forms.ToolStripItem[]
			{
				this.ToolStripDropDownButton1,
				this.ToolStripLabel1,
				this.cbTemplates,
				this.btnInsertTemplate,
				this.btnDeleteTemplate,
				this.ToolStripSeparator1,
				this.ToolStripLabel2,
				this.txtTemplateName,
				this.btnSaveTemplate
			});
			global::System.Windows.Forms.Control toolStrip = this.ToolStrip1;
			location = new global::System.Drawing.Point(0, 0);
			toolStrip.Location = location;
			this.ToolStrip1.Name = "ToolStrip1";
			global::System.Windows.Forms.Control toolStrip2 = this.ToolStrip1;
			size = new global::System.Drawing.Size(1008, 25);
			toolStrip2.Size = size;
			this.ToolStrip1.TabIndex = 158;
			this.ToolStrip1.Text = "ToolStrip1";
			this.ToolStripDropDownButton1.AutoToolTip = false;
			this.ToolStripDropDownButton1.DisplayStyle = global::System.Windows.Forms.ToolStripItemDisplayStyle.Text;
			this.ToolStripDropDownButton1.DropDownItems.AddRange(new global::System.Windows.Forms.ToolStripItem[]
			{
				this.ToolStripMenuItem1,
				this.btnFileOpen,
				this.ToolStripSeparator2,
				this.btnFileSave,
				this.btnFileSaveAs,
				this.ToolStripSeparator3,
				this.CloseToolStripMenuItem,
				this.ToolStripSeparator5,
				this.btnPrint,
				this.ToolStripSeparator4,
				this.ExitToolStripMenuItem
			});
			this.ToolStripDropDownButton1.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("ToolStripDropDownButton1.Image");
			this.ToolStripDropDownButton1.ImageTransparentColor = global::System.Drawing.Color.Magenta;
			global::System.Windows.Forms.ToolStripItem toolStripDropDownButton = this.ToolStripDropDownButton1;
			global::System.Windows.Forms.Padding margin = new global::System.Windows.Forms.Padding(0, 1, 40, 2);
			toolStripDropDownButton.Margin = margin;
			this.ToolStripDropDownButton1.Name = "ToolStripDropDownButton1";
			global::System.Windows.Forms.ToolStripItem toolStripDropDownButton2 = this.ToolStripDropDownButton1;
			size = new global::System.Drawing.Size(38, 22);
			toolStripDropDownButton2.Size = size;
			this.ToolStripDropDownButton1.Text = "File";
			this.ToolStripMenuItem1.Name = "ToolStripMenuItem1";
			global::System.Windows.Forms.ToolStripItem toolStripMenuItem = this.ToolStripMenuItem1;
			size = new global::System.Drawing.Size(145, 22);
			toolStripMenuItem.Size = size;
			this.ToolStripMenuItem1.Text = "New Drawing";
			this.btnFileOpen.Name = "btnFileOpen";
			global::System.Windows.Forms.ToolStripItem btnFileOpen = this.btnFileOpen;
			size = new global::System.Drawing.Size(145, 22);
			btnFileOpen.Size = size;
			this.btnFileOpen.Text = "Open";
			this.ToolStripSeparator2.Name = "ToolStripSeparator2";
			global::System.Windows.Forms.ToolStripItem toolStripSeparator = this.ToolStripSeparator2;
			size = new global::System.Drawing.Size(142, 6);
			toolStripSeparator.Size = size;
			this.btnFileSave.Name = "btnFileSave";
			global::System.Windows.Forms.ToolStripItem btnFileSave = this.btnFileSave;
			size = new global::System.Drawing.Size(145, 22);
			btnFileSave.Size = size;
			this.btnFileSave.Text = "Save";
			this.btnFileSave.ToolTipText = "Objects as editable";
			this.btnFileSaveAs.Name = "btnFileSaveAs";
			global::System.Windows.Forms.ToolStripItem btnFileSaveAs = this.btnFileSaveAs;
			size = new global::System.Drawing.Size(145, 22);
			btnFileSaveAs.Size = size;
			this.btnFileSaveAs.Text = "Save As";
			this.ToolStripSeparator3.Name = "ToolStripSeparator3";
			global::System.Windows.Forms.ToolStripItem toolStripSeparator2 = this.ToolStripSeparator3;
			size = new global::System.Drawing.Size(142, 6);
			toolStripSeparator2.Size = size;
			this.CloseToolStripMenuItem.Name = "CloseToolStripMenuItem";
			global::System.Windows.Forms.ToolStripItem closeToolStripMenuItem = this.CloseToolStripMenuItem;
			size = new global::System.Drawing.Size(145, 22);
			closeToolStripMenuItem.Size = size;
			this.CloseToolStripMenuItem.Text = "Close";
			this.ToolStripSeparator5.Name = "ToolStripSeparator5";
			global::System.Windows.Forms.ToolStripItem toolStripSeparator3 = this.ToolStripSeparator5;
			size = new global::System.Drawing.Size(142, 6);
			toolStripSeparator3.Size = size;
			this.btnPrint.Name = "btnPrint";
			global::System.Windows.Forms.ToolStripItem btnPrint = this.btnPrint;
			size = new global::System.Drawing.Size(145, 22);
			btnPrint.Size = size;
			this.btnPrint.Text = "Print";
			this.ToolStripSeparator4.Name = "ToolStripSeparator4";
			global::System.Windows.Forms.ToolStripItem toolStripSeparator4 = this.ToolStripSeparator4;
			size = new global::System.Drawing.Size(142, 6);
			toolStripSeparator4.Size = size;
			this.ExitToolStripMenuItem.Name = "ExitToolStripMenuItem";
			global::System.Windows.Forms.ToolStripItem exitToolStripMenuItem = this.ExitToolStripMenuItem;
			size = new global::System.Drawing.Size(145, 22);
			exitToolStripMenuItem.Size = size;
			this.ExitToolStripMenuItem.Text = "Exit";
			this.ToolStripLabel1.Name = "ToolStripLabel1";
			global::System.Windows.Forms.ToolStripItem toolStripLabel = this.ToolStripLabel1;
			size = new global::System.Drawing.Size(65, 22);
			toolStripLabel.Size = size;
			this.ToolStripLabel1.Text = "Templates:";
			this.cbTemplates.Name = "cbTemplates";
			global::System.Windows.Forms.ToolStripControlHost cbTemplates = this.cbTemplates;
			size = new global::System.Drawing.Size(220, 25);
			cbTemplates.Size = size;
			this.btnInsertTemplate.DisplayStyle = global::System.Windows.Forms.ToolStripItemDisplayStyle.Text;
			this.btnInsertTemplate.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("btnInsertTemplate.Image");
			this.btnInsertTemplate.ImageTransparentColor = global::System.Drawing.Color.Magenta;
			this.btnInsertTemplate.Name = "btnInsertTemplate";
			global::System.Windows.Forms.ToolStripItem btnInsertTemplate = this.btnInsertTemplate;
			size = new global::System.Drawing.Size(40, 22);
			btnInsertTemplate.Size = size;
			this.btnInsertTemplate.Text = "Open";
			this.btnInsertTemplate.ToolTipText = "Open Selected Template";
			this.btnDeleteTemplate.DisplayStyle = global::System.Windows.Forms.ToolStripItemDisplayStyle.Text;
			this.btnDeleteTemplate.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("btnDeleteTemplate.Image");
			this.btnDeleteTemplate.ImageTransparentColor = global::System.Drawing.Color.Magenta;
			this.btnDeleteTemplate.Name = "btnDeleteTemplate";
			global::System.Windows.Forms.ToolStripItem btnDeleteTemplate = this.btnDeleteTemplate;
			size = new global::System.Drawing.Size(44, 22);
			btnDeleteTemplate.Size = size;
			this.btnDeleteTemplate.Text = "Delete";
			this.btnDeleteTemplate.ToolTipText = "Delete Selected Template";
			global::System.Windows.Forms.ToolStripItem toolStripSeparator5 = this.ToolStripSeparator1;
			margin = new global::System.Windows.Forms.Padding(10, 0, 10, 0);
			toolStripSeparator5.Margin = margin;
			this.ToolStripSeparator1.Name = "ToolStripSeparator1";
			global::System.Windows.Forms.ToolStripItem toolStripSeparator6 = this.ToolStripSeparator1;
			size = new global::System.Drawing.Size(6, 25);
			toolStripSeparator6.Size = size;
			this.ToolStripLabel2.AccessibleDescription = "";
			this.ToolStripLabel2.Name = "ToolStripLabel2";
			global::System.Windows.Forms.ToolStripItem toolStripLabel2 = this.ToolStripLabel2;
			size = new global::System.Drawing.Size(122, 22);
			toolStripLabel2.Size = size;
			this.ToolStripLabel2.Text = "New Template Name:";
			this.txtTemplateName.Name = "txtTemplateName";
			global::System.Windows.Forms.ToolStripControlHost txtTemplateName = this.txtTemplateName;
			size = new global::System.Drawing.Size(200, 25);
			txtTemplateName.Size = size;
			this.btnSaveTemplate.DisplayStyle = global::System.Windows.Forms.ToolStripItemDisplayStyle.Text;
			this.btnSaveTemplate.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("btnSaveTemplate.Image");
			this.btnSaveTemplate.ImageTransparentColor = global::System.Drawing.Color.Magenta;
			this.btnSaveTemplate.Name = "btnSaveTemplate";
			global::System.Windows.Forms.ToolStripItem btnSaveTemplate = this.btnSaveTemplate;
			size = new global::System.Drawing.Size(35, 22);
			btnSaveTemplate.Size = size;
			this.btnSaveTemplate.Text = "Save";
			this.btnSaveTemplate.ToolTipText = "Save New Template";
			this.SaveFileDialog1.Filter = "Image .jpg |*.jpg";
			this.PrintDialog1.UseEXDialog = true;
			this.OpenFileDialog3.Filter = "Images .jpg |*.jpg";
			this.AccessibleDescription = "";
			global::System.Drawing.SizeF autoScaleDimensions = new global::System.Drawing.SizeF(6f, 13f);
			this.AutoScaleDimensions = autoScaleDimensions;
			this.AutoScaleMode = global::System.Windows.Forms.AutoScaleMode.Font;
			size = new global::System.Drawing.Size(1008, 734);
			this.ClientSize = size;
			this.Controls.Add(this.frDirection);
			this.Controls.Add(this.ToolStrip1);
			this.Controls.Add(this.frInsertableTextPhrases);
			this.Controls.Add(this.Tools);
			this.Controls.Add(this.LineTypes);
			this.Controls.Add(this.frListOfInsertableSymbols);
			this.Controls.Add(this.fraLineStyle);
			this.Controls.Add(this.frSize);
			this.Controls.Add(this.cmdInsertImage);
			this.Controls.Add(this.btnUndo);
			this.Controls.Add(this.btnPaste);
			this.Controls.Add(this.btnCopy);
			this.Controls.Add(this.btnGrid);
			this.Controls.Add(this.btnEraseScreen);
			this.Controls.Add(this.txtDrawText);
			this.Controls.Add(this.GlControl1);
			this.FormBorderStyle = global::System.Windows.Forms.FormBorderStyle.Fixed3D;
			this.Name = "frmDrawing";
			this.Text = "Utilocate Draw";
			this.frSize.ResumeLayout(false);
			this.fraLineStyle.ResumeLayout(false);
			this.frDirection.ResumeLayout(false);
			this.frInsertableTextPhrases.ResumeLayout(false);
			this.Tools.ResumeLayout(false);
			this.ToolStrip1.ResumeLayout(false);
			this.ToolStrip1.PerformLayout();
			this.ResumeLayout(false);
			this.PerformLayout();
		}

		// Token: 0x040000A0 RID: 160
		private global::System.ComponentModel.IContainer components;
	}
}
