namespace U2Drawx64
{
	// Token: 0x0200000C RID: 12
	internal partial class frmOptions : global::System.Windows.Forms.Form
	{
		// Token: 0x06000071 RID: 113 RVA: 0x0009D388 File Offset: 0x0009C388
		protected override void Dispose(bool Disposing)
		{
			if (Disposing && this.components != null)
			{
				this.components.Dispose();
			}
			base.Dispose(Disposing);
		}

		// Token: 0x06000148 RID: 328 RVA: 0x0009E468 File Offset: 0x0009D468
		[global::System.Diagnostics.DebuggerStepThrough]
		private void InitializeComponent()
		{
			this.components = new global::System.ComponentModel.Container();
			global::System.ComponentModel.ComponentResourceManager componentResourceManager = new global::System.ComponentModel.ComponentResourceManager(typeof(global::U2Drawx64.frmOptions));
			this.ToolTip1 = new global::System.Windows.Forms.ToolTip(this.components);
			this.lblUtiLocateOptions = new global::System.Windows.Forms.TabControl();
			this._SSTab1_TabPage0 = new global::System.Windows.Forms.TabPage();
			this.GroupBox1 = new global::System.Windows.Forms.GroupBox();
			this.txtDrawingDatabase = new global::System.Windows.Forms.TextBox();
			this.cmdChooseDrawingDatabase = new global::System.Windows.Forms.Button();
			this.lbDrawingDatabase = new global::System.Windows.Forms.Label();
			this.fraDBLocations_0 = new global::System.Windows.Forms.GroupBox();
			this.DataSourceLocal = new global::System.Windows.Forms.TextBox();
			this._cmdSelectFile_0 = new global::System.Windows.Forms.Button();
			this.lblUtiLocateOptions_Filename = new global::System.Windows.Forms.Label();
			this._SSTab1_TabPage1 = new global::System.Windows.Forms.TabPage();
			this.lblReportOptions_ColourPrinting_Allow = new global::System.Windows.Forms.Label();
			this.lblReportOptions_ColourPrinting = new global::System.Windows.Forms.GroupBox();
			this._obAllowColourPrinting_1 = new global::System.Windows.Forms.RadioButton();
			this._obAllowColourPrinting_0 = new global::System.Windows.Forms.RadioButton();
			this.lblReportOptions_PrimaryReportOptions = new global::System.Windows.Forms.GroupBox();
			this.btnSelectPrimaryReport = new global::System.Windows.Forms.Button();
			this.txtPrimaryReport = new global::System.Windows.Forms.TextBox();
			this.txtPrimaryReportImageHeight = new global::System.Windows.Forms.TextBox();
			this.txtPrimaryReportImageWidth = new global::System.Windows.Forms.TextBox();
			this.lblReportOptions_ValuesInMM = new global::System.Windows.Forms.Label();
			this.lblReportOptions_ImageHeight = new global::System.Windows.Forms.Label();
			this.lblReportOptions_ImageWidth = new global::System.Windows.Forms.Label();
			this.lblReportOptions_ImageSize = new global::System.Windows.Forms.Label();
			this.lblReportOptions_PrimaryReport = new global::System.Windows.Forms.Label();
			this.lblReportOptions_AuxReportOption = new global::System.Windows.Forms.GroupBox();
			this.txtAuxilaryReportImageHeight = new global::System.Windows.Forms.TextBox();
			this.txtAuxilaryReportImageWidth = new global::System.Windows.Forms.TextBox();
			this.lblReportOptions_ValuesInMM1 = new global::System.Windows.Forms.Label();
			this.lblReportOptions_Height1 = new global::System.Windows.Forms.Label();
			this.lblReportOptions_Width1 = new global::System.Windows.Forms.Label();
			this.lblReportOptions_ImageSize1 = new global::System.Windows.Forms.Label();
			this.txtAuxiliaryReport = new global::System.Windows.Forms.TextBox();
			this.lblReportOptions_Report = new global::System.Windows.Forms.Label();
			this.btnSelectAuxiliaryReport = new global::System.Windows.Forms.Button();
			this.TabPage2 = new global::System.Windows.Forms.TabPage();
			this.GroupBox6 = new global::System.Windows.Forms.GroupBox();
			this.RadioButton5 = new global::System.Windows.Forms.RadioButton();
			this.RadioButton6 = new global::System.Windows.Forms.RadioButton();
			this.GroupBox5 = new global::System.Windows.Forms.GroupBox();
			this.RadioButton3 = new global::System.Windows.Forms.RadioButton();
			this.RadioButton4 = new global::System.Windows.Forms.RadioButton();
			this.GroupBox4 = new global::System.Windows.Forms.GroupBox();
			this.RadioButton1 = new global::System.Windows.Forms.RadioButton();
			this.RadioButton2 = new global::System.Windows.Forms.RadioButton();
			this.GroupBox2 = new global::System.Windows.Forms.GroupBox();
			this.txtCompany = new global::System.Windows.Forms.TextBox();
			this.lbSelectedCompletionsForm = new global::System.Windows.Forms.Label();
			this.listbox_CompletionsForm = new global::System.Windows.Forms.ListBox();
			this.lbCompletionsForm = new global::System.Windows.Forms.Label();
			this.TabPage1 = new global::System.Windows.Forms.TabPage();
			this.cmdForcePatch = new global::System.Windows.Forms.Button();
			this.cmdDatabaseRepair = new global::System.Windows.Forms.Button();
			this.cmdLaunchLanguageSupport = new global::System.Windows.Forms.Button();
			this.TabPage3 = new global::System.Windows.Forms.TabPage();
			this.GroupBox3 = new global::System.Windows.Forms.GroupBox();
			this.ServerDocDatabaseName = new global::System.Windows.Forms.TextBox();
			this.Label6 = new global::System.Windows.Forms.Label();
			this.ServerDocDatabasePort = new global::System.Windows.Forms.TextBox();
			this.Label7 = new global::System.Windows.Forms.Label();
			this.ServerDocDatabasePassword = new global::System.Windows.Forms.TextBox();
			this.Label8 = new global::System.Windows.Forms.Label();
			this.ServerDocDatabaseUsername = new global::System.Windows.Forms.TextBox();
			this.Label9 = new global::System.Windows.Forms.Label();
			this.ServerDocDatabaseLocation = new global::System.Windows.Forms.TextBox();
			this.Label10 = new global::System.Windows.Forms.Label();
			this.fraDBLocations_1 = new global::System.Windows.Forms.GroupBox();
			this.ServerDatabaseName = new global::System.Windows.Forms.TextBox();
			this.lblUtiLocateOptions_DBName = new global::System.Windows.Forms.Label();
			this.ServerDatabasePort = new global::System.Windows.Forms.TextBox();
			this.lblUtiLocateOptions_DBPort = new global::System.Windows.Forms.Label();
			this.ServerDatabasePassword = new global::System.Windows.Forms.TextBox();
			this.lblUtiLocateOptions_DBPassword = new global::System.Windows.Forms.Label();
			this.ServerDatabaseUsername = new global::System.Windows.Forms.TextBox();
			this.lblUtiLocateOptions_DBUserName = new global::System.Windows.Forms.Label();
			this.DataSourceServer = new global::System.Windows.Forms.TextBox();
			this.lblUtiLocateOptions_DBLocation = new global::System.Windows.Forms.Label();
			this._picOptions_3 = new global::System.Windows.Forms.Panel();
			this.fraSample4 = new global::System.Windows.Forms.GroupBox();
			this._picOptions_2 = new global::System.Windows.Forms.Panel();
			this.fraSample3 = new global::System.Windows.Forms.GroupBox();
			this._picOptions_1 = new global::System.Windows.Forms.Panel();
			this.fraSample2 = new global::System.Windows.Forms.GroupBox();
			this.cmdApply = new global::System.Windows.Forms.Button();
			this.cmdCancel = new global::System.Windows.Forms.Button();
			this.cmdOK = new global::System.Windows.Forms.Button();
			this.Label1 = new global::System.Windows.Forms.Label();
			this.TextBox1 = new global::System.Windows.Forms.TextBox();
			this.TextBox2 = new global::System.Windows.Forms.TextBox();
			this.Label2 = new global::System.Windows.Forms.Label();
			this.TextBox3 = new global::System.Windows.Forms.TextBox();
			this.Label3 = new global::System.Windows.Forms.Label();
			this.TextBox4 = new global::System.Windows.Forms.TextBox();
			this.Label4 = new global::System.Windows.Forms.Label();
			this.TextBox5 = new global::System.Windows.Forms.TextBox();
			this.Label5 = new global::System.Windows.Forms.Label();
			this.txtCompletionsForm = new global::System.Windows.Forms.TextBox();
			this.cmdSelectFile = new global::Microsoft.VisualBasic.Compatibility.VB6.ButtonArray(this.components);
			this.fraDBLocations = new global::Microsoft.VisualBasic.Compatibility.VB6.GroupBoxArray(this.components);
			this.obAllowColourPrinting = new global::Microsoft.VisualBasic.Compatibility.VB6.RadioButtonArray(this.components);
			this.picOptions = new global::Microsoft.VisualBasic.Compatibility.VB6.PanelArray(this.components);
			this.txtField = new global::Microsoft.VisualBasic.Compatibility.VB6.TextBoxArray(this.components);
			this.getFile = new global::System.Windows.Forms.OpenFileDialog();
			this.imgDiv = new global::System.Windows.Forms.PictureBox();
			this.Image1 = new global::System.Windows.Forms.PictureBox();
			this.Frame1 = new global::System.Windows.Forms.Panel();
			this.lblUtiLocateLogin_Employee = new global::System.Windows.Forms.Label();
			this.lblUtiLocateOptions.SuspendLayout();
			this._SSTab1_TabPage0.SuspendLayout();
			this.GroupBox1.SuspendLayout();
			this.fraDBLocations_0.SuspendLayout();
			this._SSTab1_TabPage1.SuspendLayout();
			this.lblReportOptions_ColourPrinting.SuspendLayout();
			this.lblReportOptions_PrimaryReportOptions.SuspendLayout();
			this.lblReportOptions_AuxReportOption.SuspendLayout();
			this.TabPage2.SuspendLayout();
			this.GroupBox6.SuspendLayout();
			this.GroupBox5.SuspendLayout();
			this.GroupBox4.SuspendLayout();
			this.GroupBox2.SuspendLayout();
			this.TabPage1.SuspendLayout();
			this.TabPage3.SuspendLayout();
			this.GroupBox3.SuspendLayout();
			this.fraDBLocations_1.SuspendLayout();
			this._picOptions_3.SuspendLayout();
			this._picOptions_2.SuspendLayout();
			this._picOptions_1.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.cmdSelectFile).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.fraDBLocations).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.obAllowColourPrinting).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.picOptions).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.txtField).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.imgDiv).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.Image1).BeginInit();
			this.Frame1.SuspendLayout();
			this.SuspendLayout();
			this.lblUtiLocateOptions.Controls.Add(this._SSTab1_TabPage0);
			this.lblUtiLocateOptions.Controls.Add(this._SSTab1_TabPage1);
			this.lblUtiLocateOptions.Controls.Add(this.TabPage2);
			this.lblUtiLocateOptions.Controls.Add(this.TabPage1);
			this.lblUtiLocateOptions.Controls.Add(this.TabPage3);
			componentResourceManager.ApplyResources(this.lblUtiLocateOptions, "lblUtiLocateOptions");
			this.lblUtiLocateOptions.Multiline = true;
			this.lblUtiLocateOptions.Name = "lblUtiLocateOptions";
			this.lblUtiLocateOptions.SelectedIndex = 0;
			this._SSTab1_TabPage0.BackColor = global::System.Drawing.Color.FromArgb(224, 224, 224);
			this._SSTab1_TabPage0.Controls.Add(this.GroupBox1);
			this._SSTab1_TabPage0.Controls.Add(this.fraDBLocations_0);
			componentResourceManager.ApplyResources(this._SSTab1_TabPage0, "_SSTab1_TabPage0");
			this._SSTab1_TabPage0.Name = "_SSTab1_TabPage0";
			this._SSTab1_TabPage0.UseVisualStyleBackColor = true;
			this.GroupBox1.BackColor = global::System.Drawing.Color.White;
			this.GroupBox1.Controls.Add(this.txtDrawingDatabase);
			this.GroupBox1.Controls.Add(this.cmdChooseDrawingDatabase);
			this.GroupBox1.Controls.Add(this.lbDrawingDatabase);
			componentResourceManager.ApplyResources(this.GroupBox1, "GroupBox1");
			this.GroupBox1.ForeColor = global::System.Drawing.Color.FromArgb(0, 101, 179);
			this.GroupBox1.Name = "GroupBox1";
			this.GroupBox1.TabStop = false;
			this.txtDrawingDatabase.AcceptsReturn = true;
			this.txtDrawingDatabase.BackColor = global::System.Drawing.SystemColors.Window;
			this.txtDrawingDatabase.Cursor = global::System.Windows.Forms.Cursors.IBeam;
			componentResourceManager.ApplyResources(this.txtDrawingDatabase, "txtDrawingDatabase");
			this.txtDrawingDatabase.ForeColor = global::System.Drawing.SystemColors.WindowText;
			this.txtDrawingDatabase.Name = "txtDrawingDatabase";
			this.cmdChooseDrawingDatabase.BackColor = global::System.Drawing.SystemColors.Control;
			this.cmdChooseDrawingDatabase.Cursor = global::System.Windows.Forms.Cursors.Default;
			componentResourceManager.ApplyResources(this.cmdChooseDrawingDatabase, "cmdChooseDrawingDatabase");
			this.cmdChooseDrawingDatabase.ForeColor = global::System.Drawing.SystemColors.ControlText;
			this.cmdChooseDrawingDatabase.Name = "cmdChooseDrawingDatabase";
			this.cmdChooseDrawingDatabase.UseVisualStyleBackColor = false;
			this.lbDrawingDatabase.BackColor = global::System.Drawing.Color.White;
			this.lbDrawingDatabase.Cursor = global::System.Windows.Forms.Cursors.Default;
			componentResourceManager.ApplyResources(this.lbDrawingDatabase, "lbDrawingDatabase");
			this.lbDrawingDatabase.ForeColor = global::System.Drawing.SystemColors.ControlText;
			this.lbDrawingDatabase.Name = "lbDrawingDatabase";
			this.fraDBLocations_0.BackColor = global::System.Drawing.Color.White;
			this.fraDBLocations_0.Controls.Add(this.DataSourceLocal);
			this.fraDBLocations_0.Controls.Add(this._cmdSelectFile_0);
			this.fraDBLocations_0.Controls.Add(this.lblUtiLocateOptions_Filename);
			componentResourceManager.ApplyResources(this.fraDBLocations_0, "fraDBLocations_0");
			this.fraDBLocations_0.ForeColor = global::System.Drawing.Color.FromArgb(0, 101, 179);
			this.fraDBLocations.SetIndex(this.fraDBLocations_0, 0);
			this.fraDBLocations_0.Name = "fraDBLocations_0";
			this.fraDBLocations_0.TabStop = false;
			this.DataSourceLocal.AcceptsReturn = true;
			this.DataSourceLocal.BackColor = global::System.Drawing.SystemColors.Window;
			this.DataSourceLocal.Cursor = global::System.Windows.Forms.Cursors.IBeam;
			componentResourceManager.ApplyResources(this.DataSourceLocal, "DataSourceLocal");
			this.DataSourceLocal.ForeColor = global::System.Drawing.SystemColors.WindowText;
			this.txtField.SetIndex(this.DataSourceLocal, 0);
			this.DataSourceLocal.Name = "DataSourceLocal";
			this._cmdSelectFile_0.BackColor = global::System.Drawing.SystemColors.Control;
			this._cmdSelectFile_0.Cursor = global::System.Windows.Forms.Cursors.Default;
			componentResourceManager.ApplyResources(this._cmdSelectFile_0, "_cmdSelectFile_0");
			this._cmdSelectFile_0.ForeColor = global::System.Drawing.Color.FromArgb(0, 101, 179);
			this.cmdSelectFile.SetIndex(this._cmdSelectFile_0, 0);
			this._cmdSelectFile_0.Name = "_cmdSelectFile_0";
			this._cmdSelectFile_0.UseVisualStyleBackColor = false;
			this.lblUtiLocateOptions_Filename.BackColor = global::System.Drawing.Color.White;
			this.lblUtiLocateOptions_Filename.Cursor = global::System.Windows.Forms.Cursors.Default;
			componentResourceManager.ApplyResources(this.lblUtiLocateOptions_Filename, "lblUtiLocateOptions_Filename");
			this.lblUtiLocateOptions_Filename.ForeColor = global::System.Drawing.SystemColors.ControlText;
			this.lblUtiLocateOptions_Filename.Name = "lblUtiLocateOptions_Filename";
			this._SSTab1_TabPage1.BackColor = global::System.Drawing.Color.FromArgb(224, 224, 224);
			this._SSTab1_TabPage1.Controls.Add(this.lblReportOptions_ColourPrinting_Allow);
			this._SSTab1_TabPage1.Controls.Add(this.lblReportOptions_ColourPrinting);
			this._SSTab1_TabPage1.Controls.Add(this.lblReportOptions_PrimaryReportOptions);
			this._SSTab1_TabPage1.Controls.Add(this.lblReportOptions_AuxReportOption);
			componentResourceManager.ApplyResources(this._SSTab1_TabPage1, "_SSTab1_TabPage1");
			this._SSTab1_TabPage1.Name = "_SSTab1_TabPage1";
			this._SSTab1_TabPage1.UseVisualStyleBackColor = true;
			this.lblReportOptions_ColourPrinting_Allow.BackColor = global::System.Drawing.SystemColors.Control;
			this.lblReportOptions_ColourPrinting_Allow.Cursor = global::System.Windows.Forms.Cursors.Default;
			componentResourceManager.ApplyResources(this.lblReportOptions_ColourPrinting_Allow, "lblReportOptions_ColourPrinting_Allow");
			this.lblReportOptions_ColourPrinting_Allow.ForeColor = global::System.Drawing.SystemColors.ControlText;
			this.lblReportOptions_ColourPrinting_Allow.Name = "lblReportOptions_ColourPrinting_Allow";
			this.lblReportOptions_ColourPrinting.BackColor = global::System.Drawing.SystemColors.Control;
			this.lblReportOptions_ColourPrinting.Controls.Add(this._obAllowColourPrinting_1);
			this.lblReportOptions_ColourPrinting.Controls.Add(this._obAllowColourPrinting_0);
			componentResourceManager.ApplyResources(this.lblReportOptions_ColourPrinting, "lblReportOptions_ColourPrinting");
			this.lblReportOptions_ColourPrinting.ForeColor = global::System.Drawing.Color.FromArgb(0, 101, 179);
			this.lblReportOptions_ColourPrinting.Name = "lblReportOptions_ColourPrinting";
			this.lblReportOptions_ColourPrinting.TabStop = false;
			this._obAllowColourPrinting_1.BackColor = global::System.Drawing.SystemColors.Control;
			this._obAllowColourPrinting_1.Cursor = global::System.Windows.Forms.Cursors.Default;
			componentResourceManager.ApplyResources(this._obAllowColourPrinting_1, "_obAllowColourPrinting_1");
			this._obAllowColourPrinting_1.ForeColor = global::System.Drawing.SystemColors.ControlText;
			this.obAllowColourPrinting.SetIndex(this._obAllowColourPrinting_1, 1);
			this._obAllowColourPrinting_1.Name = "_obAllowColourPrinting_1";
			this._obAllowColourPrinting_1.TabStop = true;
			this._obAllowColourPrinting_1.UseVisualStyleBackColor = false;
			this._obAllowColourPrinting_0.BackColor = global::System.Drawing.SystemColors.Control;
			this._obAllowColourPrinting_0.Cursor = global::System.Windows.Forms.Cursors.Default;
			componentResourceManager.ApplyResources(this._obAllowColourPrinting_0, "_obAllowColourPrinting_0");
			this._obAllowColourPrinting_0.ForeColor = global::System.Drawing.SystemColors.ControlText;
			this.obAllowColourPrinting.SetIndex(this._obAllowColourPrinting_0, 0);
			this._obAllowColourPrinting_0.Name = "_obAllowColourPrinting_0";
			this._obAllowColourPrinting_0.TabStop = true;
			this._obAllowColourPrinting_0.UseVisualStyleBackColor = false;
			this.lblReportOptions_PrimaryReportOptions.BackColor = global::System.Drawing.SystemColors.Control;
			this.lblReportOptions_PrimaryReportOptions.Controls.Add(this.btnSelectPrimaryReport);
			this.lblReportOptions_PrimaryReportOptions.Controls.Add(this.txtPrimaryReport);
			this.lblReportOptions_PrimaryReportOptions.Controls.Add(this.txtPrimaryReportImageHeight);
			this.lblReportOptions_PrimaryReportOptions.Controls.Add(this.txtPrimaryReportImageWidth);
			this.lblReportOptions_PrimaryReportOptions.Controls.Add(this.lblReportOptions_ValuesInMM);
			this.lblReportOptions_PrimaryReportOptions.Controls.Add(this.lblReportOptions_ImageHeight);
			this.lblReportOptions_PrimaryReportOptions.Controls.Add(this.lblReportOptions_ImageWidth);
			this.lblReportOptions_PrimaryReportOptions.Controls.Add(this.lblReportOptions_ImageSize);
			this.lblReportOptions_PrimaryReportOptions.Controls.Add(this.lblReportOptions_PrimaryReport);
			componentResourceManager.ApplyResources(this.lblReportOptions_PrimaryReportOptions, "lblReportOptions_PrimaryReportOptions");
			this.lblReportOptions_PrimaryReportOptions.ForeColor = global::System.Drawing.Color.FromArgb(0, 101, 179);
			this.lblReportOptions_PrimaryReportOptions.Name = "lblReportOptions_PrimaryReportOptions";
			this.lblReportOptions_PrimaryReportOptions.TabStop = false;
			componentResourceManager.ApplyResources(this.btnSelectPrimaryReport, "btnSelectPrimaryReport");
			this.btnSelectPrimaryReport.Name = "btnSelectPrimaryReport";
			componentResourceManager.ApplyResources(this.txtPrimaryReport, "txtPrimaryReport");
			this.txtPrimaryReport.Name = "txtPrimaryReport";
			this.txtPrimaryReportImageHeight.AcceptsReturn = true;
			this.txtPrimaryReportImageHeight.BackColor = global::System.Drawing.SystemColors.Window;
			this.txtPrimaryReportImageHeight.Cursor = global::System.Windows.Forms.Cursors.IBeam;
			componentResourceManager.ApplyResources(this.txtPrimaryReportImageHeight, "txtPrimaryReportImageHeight");
			this.txtPrimaryReportImageHeight.ForeColor = global::System.Drawing.SystemColors.WindowText;
			this.txtPrimaryReportImageHeight.Name = "txtPrimaryReportImageHeight";
			this.txtPrimaryReportImageWidth.AcceptsReturn = true;
			this.txtPrimaryReportImageWidth.BackColor = global::System.Drawing.SystemColors.Window;
			this.txtPrimaryReportImageWidth.Cursor = global::System.Windows.Forms.Cursors.IBeam;
			componentResourceManager.ApplyResources(this.txtPrimaryReportImageWidth, "txtPrimaryReportImageWidth");
			this.txtPrimaryReportImageWidth.ForeColor = global::System.Drawing.SystemColors.WindowText;
			this.txtPrimaryReportImageWidth.Name = "txtPrimaryReportImageWidth";
			this.lblReportOptions_ValuesInMM.BackColor = global::System.Drawing.SystemColors.Control;
			this.lblReportOptions_ValuesInMM.Cursor = global::System.Windows.Forms.Cursors.Default;
			componentResourceManager.ApplyResources(this.lblReportOptions_ValuesInMM, "lblReportOptions_ValuesInMM");
			this.lblReportOptions_ValuesInMM.ForeColor = global::System.Drawing.SystemColors.ControlText;
			this.lblReportOptions_ValuesInMM.Name = "lblReportOptions_ValuesInMM";
			this.lblReportOptions_ImageHeight.BackColor = global::System.Drawing.SystemColors.Control;
			this.lblReportOptions_ImageHeight.Cursor = global::System.Windows.Forms.Cursors.Default;
			componentResourceManager.ApplyResources(this.lblReportOptions_ImageHeight, "lblReportOptions_ImageHeight");
			this.lblReportOptions_ImageHeight.ForeColor = global::System.Drawing.SystemColors.ControlText;
			this.lblReportOptions_ImageHeight.Name = "lblReportOptions_ImageHeight";
			this.lblReportOptions_ImageWidth.BackColor = global::System.Drawing.SystemColors.Control;
			this.lblReportOptions_ImageWidth.Cursor = global::System.Windows.Forms.Cursors.Default;
			componentResourceManager.ApplyResources(this.lblReportOptions_ImageWidth, "lblReportOptions_ImageWidth");
			this.lblReportOptions_ImageWidth.ForeColor = global::System.Drawing.SystemColors.ControlText;
			this.lblReportOptions_ImageWidth.Name = "lblReportOptions_ImageWidth";
			this.lblReportOptions_ImageSize.BackColor = global::System.Drawing.SystemColors.Control;
			this.lblReportOptions_ImageSize.Cursor = global::System.Windows.Forms.Cursors.Default;
			componentResourceManager.ApplyResources(this.lblReportOptions_ImageSize, "lblReportOptions_ImageSize");
			this.lblReportOptions_ImageSize.ForeColor = global::System.Drawing.SystemColors.ControlText;
			this.lblReportOptions_ImageSize.Name = "lblReportOptions_ImageSize";
			this.lblReportOptions_PrimaryReport.BackColor = global::System.Drawing.SystemColors.Control;
			this.lblReportOptions_PrimaryReport.Cursor = global::System.Windows.Forms.Cursors.Default;
			componentResourceManager.ApplyResources(this.lblReportOptions_PrimaryReport, "lblReportOptions_PrimaryReport");
			this.lblReportOptions_PrimaryReport.ForeColor = global::System.Drawing.SystemColors.ControlText;
			this.lblReportOptions_PrimaryReport.Name = "lblReportOptions_PrimaryReport";
			this.lblReportOptions_AuxReportOption.BackColor = global::System.Drawing.SystemColors.Control;
			this.lblReportOptions_AuxReportOption.Controls.Add(this.txtAuxilaryReportImageHeight);
			this.lblReportOptions_AuxReportOption.Controls.Add(this.txtAuxilaryReportImageWidth);
			this.lblReportOptions_AuxReportOption.Controls.Add(this.lblReportOptions_ValuesInMM1);
			this.lblReportOptions_AuxReportOption.Controls.Add(this.lblReportOptions_Height1);
			this.lblReportOptions_AuxReportOption.Controls.Add(this.lblReportOptions_Width1);
			this.lblReportOptions_AuxReportOption.Controls.Add(this.lblReportOptions_ImageSize1);
			this.lblReportOptions_AuxReportOption.Controls.Add(this.txtAuxiliaryReport);
			this.lblReportOptions_AuxReportOption.Controls.Add(this.lblReportOptions_Report);
			this.lblReportOptions_AuxReportOption.Controls.Add(this.btnSelectAuxiliaryReport);
			componentResourceManager.ApplyResources(this.lblReportOptions_AuxReportOption, "lblReportOptions_AuxReportOption");
			this.lblReportOptions_AuxReportOption.ForeColor = global::System.Drawing.Color.FromArgb(0, 101, 179);
			this.lblReportOptions_AuxReportOption.Name = "lblReportOptions_AuxReportOption";
			this.lblReportOptions_AuxReportOption.TabStop = false;
			this.txtAuxilaryReportImageHeight.AcceptsReturn = true;
			this.txtAuxilaryReportImageHeight.BackColor = global::System.Drawing.SystemColors.Window;
			this.txtAuxilaryReportImageHeight.Cursor = global::System.Windows.Forms.Cursors.IBeam;
			componentResourceManager.ApplyResources(this.txtAuxilaryReportImageHeight, "txtAuxilaryReportImageHeight");
			this.txtAuxilaryReportImageHeight.ForeColor = global::System.Drawing.SystemColors.WindowText;
			this.txtAuxilaryReportImageHeight.Name = "txtAuxilaryReportImageHeight";
			this.txtAuxilaryReportImageWidth.AcceptsReturn = true;
			this.txtAuxilaryReportImageWidth.BackColor = global::System.Drawing.SystemColors.Window;
			this.txtAuxilaryReportImageWidth.Cursor = global::System.Windows.Forms.Cursors.IBeam;
			componentResourceManager.ApplyResources(this.txtAuxilaryReportImageWidth, "txtAuxilaryReportImageWidth");
			this.txtAuxilaryReportImageWidth.ForeColor = global::System.Drawing.SystemColors.WindowText;
			this.txtAuxilaryReportImageWidth.Name = "txtAuxilaryReportImageWidth";
			this.lblReportOptions_ValuesInMM1.BackColor = global::System.Drawing.SystemColors.Control;
			this.lblReportOptions_ValuesInMM1.Cursor = global::System.Windows.Forms.Cursors.Default;
			componentResourceManager.ApplyResources(this.lblReportOptions_ValuesInMM1, "lblReportOptions_ValuesInMM1");
			this.lblReportOptions_ValuesInMM1.ForeColor = global::System.Drawing.SystemColors.ControlText;
			this.lblReportOptions_ValuesInMM1.Name = "lblReportOptions_ValuesInMM1";
			this.lblReportOptions_Height1.BackColor = global::System.Drawing.SystemColors.Control;
			this.lblReportOptions_Height1.Cursor = global::System.Windows.Forms.Cursors.Default;
			componentResourceManager.ApplyResources(this.lblReportOptions_Height1, "lblReportOptions_Height1");
			this.lblReportOptions_Height1.ForeColor = global::System.Drawing.SystemColors.ControlText;
			this.lblReportOptions_Height1.Name = "lblReportOptions_Height1";
			this.lblReportOptions_Width1.BackColor = global::System.Drawing.SystemColors.Control;
			this.lblReportOptions_Width1.Cursor = global::System.Windows.Forms.Cursors.Default;
			componentResourceManager.ApplyResources(this.lblReportOptions_Width1, "lblReportOptions_Width1");
			this.lblReportOptions_Width1.ForeColor = global::System.Drawing.SystemColors.ControlText;
			this.lblReportOptions_Width1.Name = "lblReportOptions_Width1";
			this.lblReportOptions_ImageSize1.BackColor = global::System.Drawing.SystemColors.Control;
			this.lblReportOptions_ImageSize1.Cursor = global::System.Windows.Forms.Cursors.Default;
			componentResourceManager.ApplyResources(this.lblReportOptions_ImageSize1, "lblReportOptions_ImageSize1");
			this.lblReportOptions_ImageSize1.ForeColor = global::System.Drawing.SystemColors.ControlText;
			this.lblReportOptions_ImageSize1.Name = "lblReportOptions_ImageSize1";
			componentResourceManager.ApplyResources(this.txtAuxiliaryReport, "txtAuxiliaryReport");
			this.txtAuxiliaryReport.Name = "txtAuxiliaryReport";
			this.lblReportOptions_Report.BackColor = global::System.Drawing.SystemColors.Control;
			this.lblReportOptions_Report.Cursor = global::System.Windows.Forms.Cursors.Default;
			componentResourceManager.ApplyResources(this.lblReportOptions_Report, "lblReportOptions_Report");
			this.lblReportOptions_Report.ForeColor = global::System.Drawing.SystemColors.ControlText;
			this.lblReportOptions_Report.Name = "lblReportOptions_Report";
			componentResourceManager.ApplyResources(this.btnSelectAuxiliaryReport, "btnSelectAuxiliaryReport");
			this.btnSelectAuxiliaryReport.Name = "btnSelectAuxiliaryReport";
			this.TabPage2.BackColor = global::System.Drawing.Color.FromArgb(224, 224, 224);
			this.TabPage2.Controls.Add(this.GroupBox6);
			this.TabPage2.Controls.Add(this.GroupBox5);
			this.TabPage2.Controls.Add(this.GroupBox4);
			this.TabPage2.Controls.Add(this.GroupBox2);
			componentResourceManager.ApplyResources(this.TabPage2, "TabPage2");
			this.TabPage2.Name = "TabPage2";
			this.TabPage2.UseVisualStyleBackColor = true;
			this.GroupBox6.BackColor = global::System.Drawing.SystemColors.Control;
			this.GroupBox6.Controls.Add(this.RadioButton5);
			this.GroupBox6.Controls.Add(this.RadioButton6);
			componentResourceManager.ApplyResources(this.GroupBox6, "GroupBox6");
			this.GroupBox6.ForeColor = global::System.Drawing.Color.FromArgb(0, 101, 179);
			this.GroupBox6.Name = "GroupBox6";
			this.GroupBox6.TabStop = false;
			this.RadioButton5.BackColor = global::System.Drawing.SystemColors.Control;
			this.RadioButton5.Cursor = global::System.Windows.Forms.Cursors.Default;
			componentResourceManager.ApplyResources(this.RadioButton5, "RadioButton5");
			this.RadioButton5.ForeColor = global::System.Drawing.SystemColors.ControlText;
			this.RadioButton5.Name = "RadioButton5";
			this.RadioButton5.TabStop = true;
			this.RadioButton5.UseVisualStyleBackColor = false;
			this.RadioButton6.BackColor = global::System.Drawing.SystemColors.Control;
			this.RadioButton6.Cursor = global::System.Windows.Forms.Cursors.Default;
			componentResourceManager.ApplyResources(this.RadioButton6, "RadioButton6");
			this.RadioButton6.ForeColor = global::System.Drawing.SystemColors.ControlText;
			this.RadioButton6.Name = "RadioButton6";
			this.RadioButton6.TabStop = true;
			this.RadioButton6.UseVisualStyleBackColor = false;
			this.GroupBox5.BackColor = global::System.Drawing.SystemColors.Control;
			this.GroupBox5.Controls.Add(this.RadioButton3);
			this.GroupBox5.Controls.Add(this.RadioButton4);
			componentResourceManager.ApplyResources(this.GroupBox5, "GroupBox5");
			this.GroupBox5.ForeColor = global::System.Drawing.Color.FromArgb(0, 101, 179);
			this.GroupBox5.Name = "GroupBox5";
			this.GroupBox5.TabStop = false;
			this.RadioButton3.BackColor = global::System.Drawing.SystemColors.Control;
			this.RadioButton3.Cursor = global::System.Windows.Forms.Cursors.Default;
			componentResourceManager.ApplyResources(this.RadioButton3, "RadioButton3");
			this.RadioButton3.ForeColor = global::System.Drawing.SystemColors.ControlText;
			this.RadioButton3.Name = "RadioButton3";
			this.RadioButton3.TabStop = true;
			this.RadioButton3.UseVisualStyleBackColor = false;
			this.RadioButton4.BackColor = global::System.Drawing.SystemColors.Control;
			this.RadioButton4.Cursor = global::System.Windows.Forms.Cursors.Default;
			componentResourceManager.ApplyResources(this.RadioButton4, "RadioButton4");
			this.RadioButton4.ForeColor = global::System.Drawing.SystemColors.ControlText;
			this.RadioButton4.Name = "RadioButton4";
			this.RadioButton4.TabStop = true;
			this.RadioButton4.UseVisualStyleBackColor = false;
			this.GroupBox4.BackColor = global::System.Drawing.SystemColors.Control;
			this.GroupBox4.Controls.Add(this.RadioButton1);
			this.GroupBox4.Controls.Add(this.RadioButton2);
			componentResourceManager.ApplyResources(this.GroupBox4, "GroupBox4");
			this.GroupBox4.ForeColor = global::System.Drawing.Color.FromArgb(0, 101, 179);
			this.GroupBox4.Name = "GroupBox4";
			this.GroupBox4.TabStop = false;
			this.RadioButton1.BackColor = global::System.Drawing.SystemColors.Control;
			this.RadioButton1.Cursor = global::System.Windows.Forms.Cursors.Default;
			componentResourceManager.ApplyResources(this.RadioButton1, "RadioButton1");
			this.RadioButton1.ForeColor = global::System.Drawing.SystemColors.ControlText;
			this.RadioButton1.Name = "RadioButton1";
			this.RadioButton1.TabStop = true;
			this.RadioButton1.UseVisualStyleBackColor = false;
			this.RadioButton2.BackColor = global::System.Drawing.SystemColors.Control;
			this.RadioButton2.Cursor = global::System.Windows.Forms.Cursors.Default;
			componentResourceManager.ApplyResources(this.RadioButton2, "RadioButton2");
			this.RadioButton2.ForeColor = global::System.Drawing.SystemColors.ControlText;
			this.RadioButton2.Name = "RadioButton2";
			this.RadioButton2.TabStop = true;
			this.RadioButton2.UseVisualStyleBackColor = false;
			this.GroupBox2.BackColor = global::System.Drawing.SystemColors.Control;
			this.GroupBox2.Controls.Add(this.txtCompany);
			this.GroupBox2.Controls.Add(this.lbSelectedCompletionsForm);
			this.GroupBox2.Controls.Add(this.listbox_CompletionsForm);
			this.GroupBox2.Controls.Add(this.lbCompletionsForm);
			componentResourceManager.ApplyResources(this.GroupBox2, "GroupBox2");
			this.GroupBox2.ForeColor = global::System.Drawing.Color.FromArgb(0, 101, 179);
			this.GroupBox2.Name = "GroupBox2";
			this.GroupBox2.TabStop = false;
			this.txtCompany.AcceptsReturn = true;
			this.txtCompany.BackColor = global::System.Drawing.SystemColors.Window;
			this.txtCompany.Cursor = global::System.Windows.Forms.Cursors.IBeam;
			this.txtCompany.ForeColor = global::System.Drawing.SystemColors.WindowText;
			componentResourceManager.ApplyResources(this.txtCompany, "txtCompany");
			this.txtCompany.Name = "txtCompany";
			this.lbSelectedCompletionsForm.BackColor = global::System.Drawing.SystemColors.Control;
			this.lbSelectedCompletionsForm.Cursor = global::System.Windows.Forms.Cursors.Default;
			componentResourceManager.ApplyResources(this.lbSelectedCompletionsForm, "lbSelectedCompletionsForm");
			this.lbSelectedCompletionsForm.ForeColor = global::System.Drawing.SystemColors.ControlText;
			this.lbSelectedCompletionsForm.Name = "lbSelectedCompletionsForm";
			this.listbox_CompletionsForm.FormattingEnabled = true;
			componentResourceManager.ApplyResources(this.listbox_CompletionsForm, "listbox_CompletionsForm");
			this.listbox_CompletionsForm.Name = "listbox_CompletionsForm";
			this.lbCompletionsForm.BackColor = global::System.Drawing.SystemColors.Control;
			this.lbCompletionsForm.Cursor = global::System.Windows.Forms.Cursors.Default;
			componentResourceManager.ApplyResources(this.lbCompletionsForm, "lbCompletionsForm");
			this.lbCompletionsForm.ForeColor = global::System.Drawing.SystemColors.ControlText;
			this.lbCompletionsForm.Name = "lbCompletionsForm";
			this.TabPage1.BackColor = global::System.Drawing.Color.FromArgb(224, 224, 224);
			this.TabPage1.Controls.Add(this.cmdForcePatch);
			this.TabPage1.Controls.Add(this.cmdDatabaseRepair);
			this.TabPage1.Controls.Add(this.cmdLaunchLanguageSupport);
			componentResourceManager.ApplyResources(this.TabPage1, "TabPage1");
			this.TabPage1.Name = "TabPage1";
			this.TabPage1.UseVisualStyleBackColor = true;
			this.cmdForcePatch.BackColor = global::System.Drawing.SystemColors.Control;
			this.cmdForcePatch.Cursor = global::System.Windows.Forms.Cursors.Default;
			componentResourceManager.ApplyResources(this.cmdForcePatch, "cmdForcePatch");
			this.cmdForcePatch.ForeColor = global::System.Drawing.SystemColors.ControlText;
			this.cmdForcePatch.Name = "cmdForcePatch";
			this.cmdForcePatch.UseVisualStyleBackColor = false;
			this.cmdDatabaseRepair.BackColor = global::System.Drawing.SystemColors.Control;
			this.cmdDatabaseRepair.Cursor = global::System.Windows.Forms.Cursors.Default;
			componentResourceManager.ApplyResources(this.cmdDatabaseRepair, "cmdDatabaseRepair");
			this.cmdDatabaseRepair.ForeColor = global::System.Drawing.SystemColors.ControlText;
			this.cmdDatabaseRepair.Name = "cmdDatabaseRepair";
			this.cmdDatabaseRepair.UseVisualStyleBackColor = false;
			this.cmdLaunchLanguageSupport.BackColor = global::System.Drawing.SystemColors.Control;
			this.cmdLaunchLanguageSupport.Cursor = global::System.Windows.Forms.Cursors.Default;
			componentResourceManager.ApplyResources(this.cmdLaunchLanguageSupport, "cmdLaunchLanguageSupport");
			this.cmdLaunchLanguageSupport.ForeColor = global::System.Drawing.SystemColors.ControlText;
			this.cmdLaunchLanguageSupport.Name = "cmdLaunchLanguageSupport";
			this.cmdLaunchLanguageSupport.UseVisualStyleBackColor = false;
			this.TabPage3.Controls.Add(this.GroupBox3);
			this.TabPage3.Controls.Add(this.fraDBLocations_1);
			componentResourceManager.ApplyResources(this.TabPage3, "TabPage3");
			this.TabPage3.Name = "TabPage3";
			this.TabPage3.UseVisualStyleBackColor = true;
			this.GroupBox3.BackColor = global::System.Drawing.Color.White;
			this.GroupBox3.Controls.Add(this.ServerDocDatabaseName);
			this.GroupBox3.Controls.Add(this.Label6);
			this.GroupBox3.Controls.Add(this.ServerDocDatabasePort);
			this.GroupBox3.Controls.Add(this.Label7);
			this.GroupBox3.Controls.Add(this.ServerDocDatabasePassword);
			this.GroupBox3.Controls.Add(this.Label8);
			this.GroupBox3.Controls.Add(this.ServerDocDatabaseUsername);
			this.GroupBox3.Controls.Add(this.Label9);
			this.GroupBox3.Controls.Add(this.ServerDocDatabaseLocation);
			this.GroupBox3.Controls.Add(this.Label10);
			componentResourceManager.ApplyResources(this.GroupBox3, "GroupBox3");
			this.GroupBox3.ForeColor = global::System.Drawing.Color.FromArgb(0, 101, 179);
			this.GroupBox3.Name = "GroupBox3";
			this.GroupBox3.TabStop = false;
			this.ServerDocDatabaseName.AcceptsReturn = true;
			this.ServerDocDatabaseName.BackColor = global::System.Drawing.SystemColors.Window;
			this.ServerDocDatabaseName.Cursor = global::System.Windows.Forms.Cursors.IBeam;
			componentResourceManager.ApplyResources(this.ServerDocDatabaseName, "ServerDocDatabaseName");
			this.ServerDocDatabaseName.ForeColor = global::System.Drawing.SystemColors.WindowText;
			this.ServerDocDatabaseName.Name = "ServerDocDatabaseName";
			this.Label6.BackColor = global::System.Drawing.Color.White;
			this.Label6.Cursor = global::System.Windows.Forms.Cursors.Default;
			componentResourceManager.ApplyResources(this.Label6, "Label6");
			this.Label6.ForeColor = global::System.Drawing.SystemColors.ControlText;
			this.Label6.Name = "Label6";
			this.ServerDocDatabasePort.AcceptsReturn = true;
			this.ServerDocDatabasePort.BackColor = global::System.Drawing.SystemColors.Window;
			this.ServerDocDatabasePort.Cursor = global::System.Windows.Forms.Cursors.IBeam;
			componentResourceManager.ApplyResources(this.ServerDocDatabasePort, "ServerDocDatabasePort");
			this.ServerDocDatabasePort.ForeColor = global::System.Drawing.SystemColors.WindowText;
			this.ServerDocDatabasePort.Name = "ServerDocDatabasePort";
			this.Label7.BackColor = global::System.Drawing.Color.White;
			this.Label7.Cursor = global::System.Windows.Forms.Cursors.Default;
			componentResourceManager.ApplyResources(this.Label7, "Label7");
			this.Label7.ForeColor = global::System.Drawing.SystemColors.ControlText;
			this.Label7.Name = "Label7";
			this.ServerDocDatabasePassword.AcceptsReturn = true;
			this.ServerDocDatabasePassword.BackColor = global::System.Drawing.SystemColors.Window;
			this.ServerDocDatabasePassword.Cursor = global::System.Windows.Forms.Cursors.IBeam;
			componentResourceManager.ApplyResources(this.ServerDocDatabasePassword, "ServerDocDatabasePassword");
			this.ServerDocDatabasePassword.ForeColor = global::System.Drawing.SystemColors.WindowText;
			this.ServerDocDatabasePassword.Name = "ServerDocDatabasePassword";
			this.Label8.BackColor = global::System.Drawing.Color.White;
			this.Label8.Cursor = global::System.Windows.Forms.Cursors.Default;
			componentResourceManager.ApplyResources(this.Label8, "Label8");
			this.Label8.ForeColor = global::System.Drawing.SystemColors.ControlText;
			this.Label8.Name = "Label8";
			this.ServerDocDatabaseUsername.AcceptsReturn = true;
			this.ServerDocDatabaseUsername.BackColor = global::System.Drawing.SystemColors.Window;
			this.ServerDocDatabaseUsername.Cursor = global::System.Windows.Forms.Cursors.IBeam;
			componentResourceManager.ApplyResources(this.ServerDocDatabaseUsername, "ServerDocDatabaseUsername");
			this.ServerDocDatabaseUsername.ForeColor = global::System.Drawing.SystemColors.WindowText;
			this.ServerDocDatabaseUsername.Name = "ServerDocDatabaseUsername";
			this.Label9.BackColor = global::System.Drawing.Color.White;
			this.Label9.Cursor = global::System.Windows.Forms.Cursors.Default;
			componentResourceManager.ApplyResources(this.Label9, "Label9");
			this.Label9.ForeColor = global::System.Drawing.SystemColors.ControlText;
			this.Label9.Name = "Label9";
			this.ServerDocDatabaseLocation.AcceptsReturn = true;
			this.ServerDocDatabaseLocation.BackColor = global::System.Drawing.SystemColors.Window;
			this.ServerDocDatabaseLocation.Cursor = global::System.Windows.Forms.Cursors.IBeam;
			componentResourceManager.ApplyResources(this.ServerDocDatabaseLocation, "ServerDocDatabaseLocation");
			this.ServerDocDatabaseLocation.ForeColor = global::System.Drawing.SystemColors.WindowText;
			this.ServerDocDatabaseLocation.Name = "ServerDocDatabaseLocation";
			this.Label10.BackColor = global::System.Drawing.Color.White;
			this.Label10.Cursor = global::System.Windows.Forms.Cursors.Default;
			componentResourceManager.ApplyResources(this.Label10, "Label10");
			this.Label10.ForeColor = global::System.Drawing.SystemColors.ControlText;
			this.Label10.Name = "Label10";
			this.fraDBLocations_1.BackColor = global::System.Drawing.Color.White;
			this.fraDBLocations_1.Controls.Add(this.ServerDatabaseName);
			this.fraDBLocations_1.Controls.Add(this.lblUtiLocateOptions_DBName);
			this.fraDBLocations_1.Controls.Add(this.ServerDatabasePort);
			this.fraDBLocations_1.Controls.Add(this.lblUtiLocateOptions_DBPort);
			this.fraDBLocations_1.Controls.Add(this.ServerDatabasePassword);
			this.fraDBLocations_1.Controls.Add(this.lblUtiLocateOptions_DBPassword);
			this.fraDBLocations_1.Controls.Add(this.ServerDatabaseUsername);
			this.fraDBLocations_1.Controls.Add(this.lblUtiLocateOptions_DBUserName);
			this.fraDBLocations_1.Controls.Add(this.DataSourceServer);
			this.fraDBLocations_1.Controls.Add(this.lblUtiLocateOptions_DBLocation);
			componentResourceManager.ApplyResources(this.fraDBLocations_1, "fraDBLocations_1");
			this.fraDBLocations_1.ForeColor = global::System.Drawing.Color.FromArgb(0, 101, 179);
			this.fraDBLocations.SetIndex(this.fraDBLocations_1, 1);
			this.fraDBLocations_1.Name = "fraDBLocations_1";
			this.fraDBLocations_1.TabStop = false;
			this.ServerDatabaseName.AcceptsReturn = true;
			this.ServerDatabaseName.BackColor = global::System.Drawing.SystemColors.Window;
			this.ServerDatabaseName.Cursor = global::System.Windows.Forms.Cursors.IBeam;
			componentResourceManager.ApplyResources(this.ServerDatabaseName, "ServerDatabaseName");
			this.ServerDatabaseName.ForeColor = global::System.Drawing.SystemColors.WindowText;
			this.ServerDatabaseName.Name = "ServerDatabaseName";
			this.lblUtiLocateOptions_DBName.BackColor = global::System.Drawing.Color.White;
			this.lblUtiLocateOptions_DBName.Cursor = global::System.Windows.Forms.Cursors.Default;
			componentResourceManager.ApplyResources(this.lblUtiLocateOptions_DBName, "lblUtiLocateOptions_DBName");
			this.lblUtiLocateOptions_DBName.ForeColor = global::System.Drawing.SystemColors.ControlText;
			this.lblUtiLocateOptions_DBName.Name = "lblUtiLocateOptions_DBName";
			this.ServerDatabasePort.AcceptsReturn = true;
			this.ServerDatabasePort.BackColor = global::System.Drawing.SystemColors.Window;
			this.ServerDatabasePort.Cursor = global::System.Windows.Forms.Cursors.IBeam;
			componentResourceManager.ApplyResources(this.ServerDatabasePort, "ServerDatabasePort");
			this.ServerDatabasePort.ForeColor = global::System.Drawing.SystemColors.WindowText;
			this.ServerDatabasePort.Name = "ServerDatabasePort";
			this.lblUtiLocateOptions_DBPort.BackColor = global::System.Drawing.Color.White;
			this.lblUtiLocateOptions_DBPort.Cursor = global::System.Windows.Forms.Cursors.Default;
			componentResourceManager.ApplyResources(this.lblUtiLocateOptions_DBPort, "lblUtiLocateOptions_DBPort");
			this.lblUtiLocateOptions_DBPort.ForeColor = global::System.Drawing.SystemColors.ControlText;
			this.lblUtiLocateOptions_DBPort.Name = "lblUtiLocateOptions_DBPort";
			this.ServerDatabasePassword.AcceptsReturn = true;
			this.ServerDatabasePassword.BackColor = global::System.Drawing.SystemColors.Window;
			this.ServerDatabasePassword.Cursor = global::System.Windows.Forms.Cursors.IBeam;
			componentResourceManager.ApplyResources(this.ServerDatabasePassword, "ServerDatabasePassword");
			this.ServerDatabasePassword.ForeColor = global::System.Drawing.SystemColors.WindowText;
			this.ServerDatabasePassword.Name = "ServerDatabasePassword";
			this.lblUtiLocateOptions_DBPassword.BackColor = global::System.Drawing.Color.White;
			this.lblUtiLocateOptions_DBPassword.Cursor = global::System.Windows.Forms.Cursors.Default;
			componentResourceManager.ApplyResources(this.lblUtiLocateOptions_DBPassword, "lblUtiLocateOptions_DBPassword");
			this.lblUtiLocateOptions_DBPassword.ForeColor = global::System.Drawing.SystemColors.ControlText;
			this.lblUtiLocateOptions_DBPassword.Name = "lblUtiLocateOptions_DBPassword";
			this.ServerDatabaseUsername.AcceptsReturn = true;
			this.ServerDatabaseUsername.BackColor = global::System.Drawing.SystemColors.Window;
			this.ServerDatabaseUsername.Cursor = global::System.Windows.Forms.Cursors.IBeam;
			componentResourceManager.ApplyResources(this.ServerDatabaseUsername, "ServerDatabaseUsername");
			this.ServerDatabaseUsername.ForeColor = global::System.Drawing.SystemColors.WindowText;
			this.ServerDatabaseUsername.Name = "ServerDatabaseUsername";
			this.lblUtiLocateOptions_DBUserName.BackColor = global::System.Drawing.Color.White;
			this.lblUtiLocateOptions_DBUserName.Cursor = global::System.Windows.Forms.Cursors.Default;
			componentResourceManager.ApplyResources(this.lblUtiLocateOptions_DBUserName, "lblUtiLocateOptions_DBUserName");
			this.lblUtiLocateOptions_DBUserName.ForeColor = global::System.Drawing.SystemColors.ControlText;
			this.lblUtiLocateOptions_DBUserName.Name = "lblUtiLocateOptions_DBUserName";
			this.DataSourceServer.AcceptsReturn = true;
			this.DataSourceServer.BackColor = global::System.Drawing.SystemColors.Window;
			this.DataSourceServer.Cursor = global::System.Windows.Forms.Cursors.IBeam;
			componentResourceManager.ApplyResources(this.DataSourceServer, "DataSourceServer");
			this.DataSourceServer.ForeColor = global::System.Drawing.SystemColors.WindowText;
			this.txtField.SetIndex(this.DataSourceServer, 1);
			this.DataSourceServer.Name = "DataSourceServer";
			this.lblUtiLocateOptions_DBLocation.BackColor = global::System.Drawing.Color.White;
			this.lblUtiLocateOptions_DBLocation.Cursor = global::System.Windows.Forms.Cursors.Default;
			componentResourceManager.ApplyResources(this.lblUtiLocateOptions_DBLocation, "lblUtiLocateOptions_DBLocation");
			this.lblUtiLocateOptions_DBLocation.ForeColor = global::System.Drawing.SystemColors.ControlText;
			this.lblUtiLocateOptions_DBLocation.Name = "lblUtiLocateOptions_DBLocation";
			this._picOptions_3.BackColor = global::System.Drawing.SystemColors.Control;
			this._picOptions_3.Controls.Add(this.fraSample4);
			this._picOptions_3.Cursor = global::System.Windows.Forms.Cursors.Default;
			componentResourceManager.ApplyResources(this._picOptions_3, "_picOptions_3");
			this._picOptions_3.ForeColor = global::System.Drawing.SystemColors.ControlText;
			this.picOptions.SetIndex(this._picOptions_3, 3);
			this._picOptions_3.Name = "_picOptions_3";
			this.fraSample4.BackColor = global::System.Drawing.SystemColors.Control;
			componentResourceManager.ApplyResources(this.fraSample4, "fraSample4");
			this.fraSample4.ForeColor = global::System.Drawing.SystemColors.ControlText;
			this.fraSample4.Name = "fraSample4";
			this.fraSample4.TabStop = false;
			this._picOptions_2.BackColor = global::System.Drawing.SystemColors.Control;
			this._picOptions_2.Controls.Add(this.fraSample3);
			this._picOptions_2.Cursor = global::System.Windows.Forms.Cursors.Default;
			componentResourceManager.ApplyResources(this._picOptions_2, "_picOptions_2");
			this._picOptions_2.ForeColor = global::System.Drawing.SystemColors.ControlText;
			this.picOptions.SetIndex(this._picOptions_2, 2);
			this._picOptions_2.Name = "_picOptions_2";
			this.fraSample3.BackColor = global::System.Drawing.SystemColors.Control;
			componentResourceManager.ApplyResources(this.fraSample3, "fraSample3");
			this.fraSample3.ForeColor = global::System.Drawing.SystemColors.ControlText;
			this.fraSample3.Name = "fraSample3";
			this.fraSample3.TabStop = false;
			this._picOptions_1.BackColor = global::System.Drawing.SystemColors.Control;
			this._picOptions_1.Controls.Add(this.fraSample2);
			this._picOptions_1.Cursor = global::System.Windows.Forms.Cursors.Default;
			componentResourceManager.ApplyResources(this._picOptions_1, "_picOptions_1");
			this._picOptions_1.ForeColor = global::System.Drawing.SystemColors.ControlText;
			this.picOptions.SetIndex(this._picOptions_1, 1);
			this._picOptions_1.Name = "_picOptions_1";
			this.fraSample2.BackColor = global::System.Drawing.SystemColors.Control;
			componentResourceManager.ApplyResources(this.fraSample2, "fraSample2");
			this.fraSample2.ForeColor = global::System.Drawing.SystemColors.ControlText;
			this.fraSample2.Name = "fraSample2";
			this.fraSample2.TabStop = false;
			this.cmdApply.BackColor = global::System.Drawing.SystemColors.Control;
			this.cmdApply.Cursor = global::System.Windows.Forms.Cursors.Default;
			componentResourceManager.ApplyResources(this.cmdApply, "cmdApply");
			this.cmdApply.ForeColor = global::System.Drawing.SystemColors.ControlText;
			this.cmdApply.Image = global::U2Drawx64.My.Resources.Resources.save;
			this.cmdApply.Name = "cmdApply";
			this.cmdApply.UseVisualStyleBackColor = false;
			this.cmdCancel.BackColor = global::System.Drawing.SystemColors.Control;
			this.cmdCancel.Cursor = global::System.Windows.Forms.Cursors.IBeam;
			this.cmdCancel.DialogResult = global::System.Windows.Forms.DialogResult.Cancel;
			componentResourceManager.ApplyResources(this.cmdCancel, "cmdCancel");
			this.cmdCancel.ForeColor = global::System.Drawing.SystemColors.ControlText;
			this.cmdCancel.Image = global::U2Drawx64.My.Resources.Resources.cancel;
			this.cmdCancel.Name = "cmdCancel";
			this.cmdCancel.UseVisualStyleBackColor = false;
			this.cmdOK.BackColor = global::System.Drawing.SystemColors.Control;
			this.cmdOK.Cursor = global::System.Windows.Forms.Cursors.Default;
			componentResourceManager.ApplyResources(this.cmdOK, "cmdOK");
			this.cmdOK.ForeColor = global::System.Drawing.SystemColors.ControlText;
			this.cmdOK.Image = global::U2Drawx64.My.Resources.Resources.tick;
			this.cmdOK.Name = "cmdOK";
			this.cmdOK.UseVisualStyleBackColor = false;
			this.Label1.ForeColor = global::System.Drawing.Color.Black;
			componentResourceManager.ApplyResources(this.Label1, "Label1");
			this.Label1.Name = "Label1";
			componentResourceManager.ApplyResources(this.TextBox1, "TextBox1");
			this.TextBox1.Name = "TextBox1";
			this.TextBox2.AcceptsReturn = true;
			this.TextBox2.BackColor = global::System.Drawing.SystemColors.Window;
			this.TextBox2.Cursor = global::System.Windows.Forms.Cursors.IBeam;
			componentResourceManager.ApplyResources(this.TextBox2, "TextBox2");
			this.TextBox2.ForeColor = global::System.Drawing.SystemColors.WindowText;
			this.TextBox2.Name = "TextBox2";
			this.Label2.BackColor = global::System.Drawing.SystemColors.Control;
			this.Label2.Cursor = global::System.Windows.Forms.Cursors.Default;
			componentResourceManager.ApplyResources(this.Label2, "Label2");
			this.Label2.ForeColor = global::System.Drawing.SystemColors.ControlText;
			this.Label2.Name = "Label2";
			this.TextBox3.AcceptsReturn = true;
			this.TextBox3.BackColor = global::System.Drawing.SystemColors.Window;
			this.TextBox3.Cursor = global::System.Windows.Forms.Cursors.IBeam;
			componentResourceManager.ApplyResources(this.TextBox3, "TextBox3");
			this.TextBox3.ForeColor = global::System.Drawing.SystemColors.WindowText;
			this.TextBox3.Name = "TextBox3";
			this.Label3.BackColor = global::System.Drawing.SystemColors.Control;
			this.Label3.Cursor = global::System.Windows.Forms.Cursors.Default;
			componentResourceManager.ApplyResources(this.Label3, "Label3");
			this.Label3.ForeColor = global::System.Drawing.SystemColors.ControlText;
			this.Label3.Name = "Label3";
			this.TextBox4.AcceptsReturn = true;
			this.TextBox4.BackColor = global::System.Drawing.SystemColors.Window;
			this.TextBox4.Cursor = global::System.Windows.Forms.Cursors.IBeam;
			componentResourceManager.ApplyResources(this.TextBox4, "TextBox4");
			this.TextBox4.ForeColor = global::System.Drawing.SystemColors.WindowText;
			this.TextBox4.Name = "TextBox4";
			this.Label4.BackColor = global::System.Drawing.SystemColors.Control;
			this.Label4.Cursor = global::System.Windows.Forms.Cursors.Default;
			componentResourceManager.ApplyResources(this.Label4, "Label4");
			this.Label4.ForeColor = global::System.Drawing.SystemColors.ControlText;
			this.Label4.Name = "Label4";
			this.TextBox5.AcceptsReturn = true;
			this.TextBox5.BackColor = global::System.Drawing.SystemColors.Window;
			this.TextBox5.Cursor = global::System.Windows.Forms.Cursors.IBeam;
			componentResourceManager.ApplyResources(this.TextBox5, "TextBox5");
			this.TextBox5.ForeColor = global::System.Drawing.SystemColors.WindowText;
			this.TextBox5.Name = "TextBox5";
			this.Label5.BackColor = global::System.Drawing.SystemColors.Control;
			this.Label5.Cursor = global::System.Windows.Forms.Cursors.Default;
			componentResourceManager.ApplyResources(this.Label5, "Label5");
			this.Label5.ForeColor = global::System.Drawing.SystemColors.ControlText;
			this.Label5.Name = "Label5";
			this.txtCompletionsForm.AcceptsReturn = true;
			this.txtCompletionsForm.BackColor = global::System.Drawing.SystemColors.Window;
			this.txtCompletionsForm.Cursor = global::System.Windows.Forms.Cursors.IBeam;
			componentResourceManager.ApplyResources(this.txtCompletionsForm, "txtCompletionsForm");
			this.txtCompletionsForm.ForeColor = global::System.Drawing.SystemColors.WindowText;
			this.txtCompletionsForm.Name = "txtCompletionsForm";
			componentResourceManager.ApplyResources(this.getFile, "getFile");
			this.imgDiv.Cursor = global::System.Windows.Forms.Cursors.Default;
			componentResourceManager.ApplyResources(this.imgDiv, "imgDiv");
			this.imgDiv.Name = "imgDiv";
			this.imgDiv.TabStop = false;
			this.Image1.Cursor = global::System.Windows.Forms.Cursors.Default;
			componentResourceManager.ApplyResources(this.Image1, "Image1");
			this.Image1.Name = "Image1";
			this.Image1.TabStop = false;
			this.Frame1.BackColor = global::System.Drawing.Color.Gainsboro;
			this.Frame1.Controls.Add(this.lblUtiLocateLogin_Employee);
			this.Frame1.Controls.Add(this.imgDiv);
			this.Frame1.Controls.Add(this.Image1);
			this.Frame1.Cursor = global::System.Windows.Forms.Cursors.Default;
			componentResourceManager.ApplyResources(this.Frame1, "Frame1");
			this.Frame1.ForeColor = global::System.Drawing.SystemColors.ControlText;
			this.Frame1.Name = "Frame1";
			this.lblUtiLocateLogin_Employee.BackColor = global::System.Drawing.Color.Transparent;
			this.lblUtiLocateLogin_Employee.Cursor = global::System.Windows.Forms.Cursors.Default;
			componentResourceManager.ApplyResources(this.lblUtiLocateLogin_Employee, "lblUtiLocateLogin_Employee");
			this.lblUtiLocateLogin_Employee.ForeColor = global::System.Drawing.Color.Black;
			this.lblUtiLocateLogin_Employee.Name = "lblUtiLocateLogin_Employee";
			componentResourceManager.ApplyResources(this, "$this");
			this.BackColor = global::System.Drawing.Color.White;
			this.Controls.Add(this.Frame1);
			this.Controls.Add(this.lblUtiLocateOptions);
			this.Controls.Add(this._picOptions_3);
			this.Controls.Add(this._picOptions_2);
			this.Controls.Add(this._picOptions_1);
			this.Controls.Add(this.cmdApply);
			this.Controls.Add(this.cmdCancel);
			this.Controls.Add(this.cmdOK);
			this.Cursor = global::System.Windows.Forms.Cursors.Default;
			this.FormBorderStyle = global::System.Windows.Forms.FormBorderStyle.FixedDialog;
			this.KeyPreview = true;
			this.MaximizeBox = false;
			this.MinimizeBox = false;
			this.Name = "frmOptions";
			this.ShowInTaskbar = false;
			this.lblUtiLocateOptions.ResumeLayout(false);
			this._SSTab1_TabPage0.ResumeLayout(false);
			this.GroupBox1.ResumeLayout(false);
			this.GroupBox1.PerformLayout();
			this.fraDBLocations_0.ResumeLayout(false);
			this.fraDBLocations_0.PerformLayout();
			this._SSTab1_TabPage1.ResumeLayout(false);
			this.lblReportOptions_ColourPrinting.ResumeLayout(false);
			this.lblReportOptions_PrimaryReportOptions.ResumeLayout(false);
			this.lblReportOptions_PrimaryReportOptions.PerformLayout();
			this.lblReportOptions_AuxReportOption.ResumeLayout(false);
			this.lblReportOptions_AuxReportOption.PerformLayout();
			this.TabPage2.ResumeLayout(false);
			this.GroupBox6.ResumeLayout(false);
			this.GroupBox5.ResumeLayout(false);
			this.GroupBox4.ResumeLayout(false);
			this.GroupBox2.ResumeLayout(false);
			this.GroupBox2.PerformLayout();
			this.TabPage1.ResumeLayout(false);
			this.TabPage3.ResumeLayout(false);
			this.GroupBox3.ResumeLayout(false);
			this.GroupBox3.PerformLayout();
			this.fraDBLocations_1.ResumeLayout(false);
			this.fraDBLocations_1.PerformLayout();
			this._picOptions_3.ResumeLayout(false);
			this._picOptions_2.ResumeLayout(false);
			this._picOptions_1.ResumeLayout(false);
			((global::System.ComponentModel.ISupportInitialize)this.cmdSelectFile).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.fraDBLocations).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.obAllowColourPrinting).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.picOptions).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.txtField).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.imgDiv).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.Image1).EndInit();
			this.Frame1.ResumeLayout(false);
			this.ResumeLayout(false);
		}

		// Token: 0x0400002F RID: 47
		private global::System.ComponentModel.IContainer components;

		// Token: 0x04000030 RID: 48
		public global::System.Windows.Forms.ToolTip ToolTip1;
	}
}
